### ISSUE TITLE
Allow manual % of premium in trading

### ISSUE THREAD

**Issue by arturodelia** [mycelium-com/wallet#100]
Currently, in Argentina, the going rate for a bitcoin is over the 35% maximum allowed to set in the advertisement of the trading function of Mycelium. I cannot set an ad out because of this limitation (false advertising). Not sure the reason to have fixed levels, but I suggest removing the fixed limitation and allow manual entry of whatever premium we choose.

**Comment by DanielWeigl** [comment]
Is now available, its called "XAR"
