### ISSUE TITLE
Problem with QR reasding and pasting from clipboard

### ISSUE THREAD

**Issue by ebuchman** [mycelium-com/wallet#104]
So for some reason the QR reader in my mycelium app won't work. I'm on Android 4.1.2 with mycelium 1.2.12 on a Sony Xperia Ion. I can use another app, NeoReader, to read the QR (seemlessly), but when I then copy the result to clipboard, mycelium doesn't let me paste, even though my browser or a notepad does.

Love this app, but this is killing me. Any ideas?

**Comment by Giszmo** [comment]
no reply? closing ...
