### ISSUE TITLE
testnet block height differs from consensus

### ISSUE THREAD

**Issue by carryforward** [mycelium-com/wallet#107]
My confirmed transactions are being shown at a different height from these other services:

http://blockexplorer.com
https://chain.so
https://www.biteasy.com/testnet
http://tbtc.blockr.io

The confirmation height also differs from by BTCD client/wallet software which sent the transaction.

The field "Confirmed in block" shows a number 1 lower than the above listed services.

This has happened in two seperate transactions, so it is unlikely to be an orphaning issue.

The wallet software does not show the block hash, so height is the only way to differentiate blocks in mycelium, but it is incorrect.

I am running the latest version of mycelium testnet on the google play store.  I am using the mycelium testnet client on android 4.4.4.

**Comment by Giszmo** [comment]
you can check the block hash via the transaction details' link to a block explorer. A one-off issue sounds like 0-based counting vs. 1-based counting and nothing critical. Closing. Reopen if you see this differently.
