### ISSUE TITLE
No local trader account associated with this wallet

### ISSUE THREAD

**Issue by wksantiago** [mycelium-com/wallet#108]
I recently restored my Mycelium Wallet in a new smartphone.  I was able to recover the wallet and recovered my private key.  All OK

When I went to "Buy / Sell Bitcoin" and went to "My Info"

It is asking to "Create"

It goes to "Creating Trader Account"  and under Choose the Bitcoin address you wish to link to your trader account:

There is none.  It is empty.

How can I restore my "My Info"?

Thanks,

**Comment by Giszmo** [comment]
no reply. closing.
