### ISSUE TITLE
Incorrect local trader price/fees calculation.

### ISSUE THREAD

**Issue by Poryhack** [mycelium-com/wallet#114]
I currently have two sell ads open. One is set at Coinbase +0% and the other is set at Coinbase +13%. When I visit the "buy bitcoin" tab I see my Coinbase +0% ad priced at 404.96. All fine and dandy. But my Coinbase +13% ad is at 465.47. Doing the math, I would expect my +13% ad to be 404.96 \* 1.13 = 457.60. That's a full 7.87 dollars per BTC (1.7%) off from the actual price on my Coinbase +13% ad.

I have tried to come up with a reason for this discrepancy but I can't; I believe there is a significant issue here.

**Comment by SimonBelmond** [comment]
Agree that this is confusing. When I see X+13% I expect X + 0.13 * X = final price

not

final price - 0.13 * final prize = X

**Comment by Giszmo** [comment]
As users get confused by this, it's a bug. Either a bug in not explaining it right or in not implementing it right and I tend to agree with OP's expectation. But what to do about it?

**Comment by Giszmo** [comment]
Cleaning up the bug tracker. This issue was not raised in 1.5a. Closing for now.
