### ISSUE TITLE
 a pin reset function in the wallet

### ISSUE THREAD

**Issue by uzimedia** [mycelium-com/wallet#115]
Hi Andreas
its the end of semptember
you wrote me in the past
3) it is possible that we enable a pin reset function in the wallet, but it is not clear if it is even a good idea, but if we implement it - it will not be deployed until september.
[regarding about the pin code]
can you help me now please?
best regards
Uzi

**Comment by DanielWeigl** [comment]
Is available - with a forced waiting period of 2 weeks. You also have the choice to make the PIN un-resettable, if you like. Then your only chance after forgetting it, is to recover from your masterseed backup.
