### ISSUE TITLE
Allow spending zero confirmation UTXO

### ISSUE THREAD

**Issue by slush0** [mycelium-com/wallet#116]
Hi,

please allow to spend unconfirmed transactions, as is usual in another bitcoin wallets. This is especially useful for mobile application like Mycelium, where transactions are done face-to-face and waiting for confirmations is extremely inconvenient.

I'm especially interested in the possibility of spending unconfirmed tx from cold storage / paper wallet.

I'm willing to pay a bounty of 1BTC for implementing / integrating this feature into Mycelium.

**Comment by tchoulihan** [comment]
I need this feature baadly. The mycelium testnet wallet is useless today because testnet3 has reset, and everything is 0 confirmations.

**Comment by DanielWeigl** [comment]
Current beta has it enabled, will get released within next week
