### ISSUE TITLE
v2.0.2 has bug and not standard behaviour BIP44

### ISSUE THREAD

**Issue by Perlover** [mycelium-com/wallet#119]
Hi,

You forgot about compute ahead change addresses -> incorrect balance if i restored wallet or have copy of seed in other device.

I have set up one seed for two devices with Mycelium 2.0.2
In first device i made payment from Account 1 to Account 2 but not full sum of bitcoins. So part of bitcoins were moved to change address. But other device didn't compute ahead change address and don't know about used change address. The result - incorrect balance in other device of Account 1 - zero but i had there some bitcoins in change addresses ;-) ...

And as i see you  work not by standard BIP44.

BIP44 (or BIP32 - i don't remember) - it claims to recompute ahead addresses with gap maximum 20 addresses after last used address. You don't this. You have only gap as '1' for account addresses and '0' gap for a change addresses. Should be there 20 for both types.

So if i will restore from seed wallet of BIP44 in Mycelium - i will see incorrect balances in all accounts if there are some gaps from 2 up to 19 not-used addresses and if there are some change addresses...

**Comment by Giszmo** [comment]
Can we close issues that didn't get a comment in a year more easily? I assume this one is resolved since long.
