### ISSUE TITLE
One, ENORMOUS request - aggregate view

### ISSUE THREAD

**Issue by silverdr** [mycelium-com/wallet#121]
Please, PLEASE put the aggregate view back-in. It's been one of the basic functionalities I praised Mycelium for. It *IS* extremely helpful and needed for effective managing bigger number of accounts. Therefore - once more - PLEASE put it back in.

**Comment by DanielWeigl** [comment]
We no show the cumulative balance for "HD" accounts and  "Other" accounts and the overall balance in the "Accounts" Tab. Hope that fixes that issue.
