### ISSUE TITLE
Transactions Page: Destination BTC-Address dosn't show up any more

### ISSUE THREAD

**Issue by smily111** [mycelium-com/wallet#123]
Since the HD Update the destination BTC-Address or the assigned address book entry dosn't show up any more.
Just date, amount and number of confirmations.

I know there is a new feature to label transactions, but I already entered all my destination addresses into the address book (100+) to get my transactions "labeled" in the previous software version - and want to avoid labeling them all again!

Please display the BTC-Address/assigned address book entry at the transaction Page!

**Comment by Giszmo** [comment]
transactions are labled according to address book entries. closing.
