### ISSUE TITLE
Can't delete/archive unused HD wallet.

### ISSUE THREAD

**Issue by dpc** [mycelium-com/wallet#127]
I wanted to import a Trezor-generated wordlist to test backup import into Mycelium Wallet, but I already had a generated HD wallet, that I have never used. I was stuck because:
- I can't archive/delete the unused HD wallet
- I can't import HD wallet if I already have a HD wallet

**Comment by keo** [comment]
Same here. Want to use Mycelium with only a Trezor, I don't need the HD wallet. I also want to set a PIN on Mycelium so it doesn't show the Trezor balances... But without backup my HD wallet it won't let me setup a PIN. I don't need that unused HD wallet, but I still need to back it up to be able to setup a PIN on Mycelium... This is a bit cumbersome :)

**Comment by jandreske** [comment]
Hmm, true - the use case of not having active accounts in the wallet but use it to monitor other accounts and just for cold spending did not occur to us. And it probably wasnt a real use case before trezor support was added. I really dont know if (and if, how) we should support a "light" wallet usage with no funds on the phone and just cold spending capabilities.... we need to discuss this. And I do not know when we will find the time - so maybe you just have to live with an unused, backed up account for now.

**Comment by Giszmo** [comment]
What I would want multiple master seeds for, would be … to make things worse … to verify backups, including my own backup. Are my 12 words really enough to restore it all? How about the coinapult and the LT accounts? Or was I importing LT from a legacy account? And if so, how do I get it over?

Also I suspect somebody might have found my 12-words containing important-paper collection: I would like to create a new master account on a device that holds the old one, to send over my funds. Currently I need two phones for that.

**Comment by jandreske** [comment]
At least parts of that can be covered with the current wallet. To see whether you cann access funds on a backup, open the menu, select offline wallet, select master seed, type the backup, see whether you get access to spend the funds.
Same works if you want to migrate, make sure you have a backup of everything, wipe app data, generate new, then use offline wallet to do cold spending from the old master seed to your new account.

**Comment by Giszmo** [comment]
But it's a leap of faith to delete the original before recovering it on the destination. That's why people don't try it until they lose their phone.

**Comment by jandreske** [comment]
Well, just use the testnet wallet to test stuff then ☺

-------- Ursprüngliche Nachricht --------
Von: Leo Wandersleb <notifications@github.com> 
Datum: 19.12.2015  20:25  (GMT-08:00) 
An: mycelium-com/wallet <wallet@noreply.github.com> 
Cc: Jan Dreske <jandreske@web.de> 
Betreff: Re: [wallet] Can't delete/archive unused HD wallet. (#127) 

But it's a leap of faith to delete the original before recovering it on the destination. That's why people don't try it until they lose their phone.

**Comment by Giszmo** [comment]
Come on. Us devs know all this but how many people lost their coins cause they thought they were backed up somewhere? A secure way to check your backup is almost as essential as the backup itself.

**Comment by tphyahoo** [comment]
Assuming mycelium is standard bip44 wallet with bip39 seed phrase (I think it is, but not 100%), one can verify the mycelium backup on any bip44 compatible wallet.  I think breadwallet, multibit, and many other wallets follow this standard.

This could be added to docu/wiki and current bug closed?

**Comment by Giszmo** [comment]
@tphyahoo trusting any wallet is already a challenge for a security minded person. Telling the users to go trust another wallet to test their backup would require the user to trust both wallets.

Other than that, yes, Mycelium is fully compliant with BIP39/44.

**Comment by tphyahoo** [comment]
Use throwaway wallets to gain confidence.  Create in one sytem, transfer in token amount of funds, restore in different system, confirm funds are still there.

A little hacky, but reasonable I think.

**Comment by MarcusMM2** [comment]
same for me, I have a TREZOR account and want to delete standard HD wallet
