### ISSUE TITLE
Better backup and restore seed

### ISSUE THREAD

**Issue by ondra-novak** [mycelium-com/wallet#130]
I am understand, why Trezor is forcing poeple to write down 12 or 18 worlds that are encoding the master seed. It is a small device with a small display. But this can be done better in a device with the large display and with the camera in it.

My suggestions
* export seed as QR code. 
* export seed as encrypted QR code
* allow to import seed by scanning QR code (also encrypted)
* Use legacy PDF backup to store seed (encrypted) and to restore it.

My backup now looks like piece of paper with words written by hand. It can be easy recycled by an accident. Paper, which looks more like important document can have better future. And with encryption, I can create multiple papers and put them to various places without dangerous of unauthorized manipulation with them.

**Comment by Giszmo** [comment]
fixed
