### ISSUE TITLE
i dont remember my pin code

### ISSUE THREAD

**Issue by uzimedia** [mycelium-com/wallet#137]
and i want to send bitcoin from one address to another address all are mine
![2014-12-02 09 38 15](https://cloud.githubusercontent.com/assets/7235377/5260494/2de6f71c-7a18-11e4-91f2-27a15c919307.png)
![2014-12-02 09 33 09](https://cloud.githubusercontent.com/assets/7235377/5260497/3136f52a-7a18-11e4-8475-6549af6b7bfc.png)
i understand that  the beta channel for a version of mycelium that has a pin reset function
but i dont know what to do?
i dont have a rooted phone
i have mycelium app on my phone long time ago
i want to solve this asap
tnx 
Uzi

**Comment by jandreske** [comment]
PINs can now be resettable (user choice upon setting the PIN) and resettable PINs and those created before the choice was present can be reset with a delay - to avoid others resetting a PIN without giving the owner enough time to move funds from a backup.
