### ISSUE TITLE
RFC6979 Deterministic Signatures?

### ISSUE THREAD

**Issue by dabura667** [mycelium-com/wallet#141]
Does Mycelium support them? If not, are there any plans to support them?

**Comment by dabura667** [comment]
https://github.com/bitpay/bitcore/blob/master/test/data/ecdsa.json#L158

Here are test vectors.

Message is hashed once with sha256 to get the digest.

k_bad00 is normal output assuming no failures.
k_badxx is the output assuming xx failures. (Since bitcore uses a counter every time the r or s is invalid, they can test as many error loops as they want)

All these vectors were verified against python-ecdsa with a simple 2 line modification to allow a counter for the error loop.

Hope you guys can comply with RFC6979. :-)

**Comment by dabura667** [comment]
Any update on this?

**Comment by Giszmo** [comment]
this should be fixed already according to commit messages

**Comment by dabura667** [comment]
Yep, bouncycastle did in fact implement RFC 6979:
https://github.com/rtyley/spongycastle/blob/2053b7050ae046b9a54ff96019dc4e2d813d1741/core/src/main/java/org/spongycastle/crypto/signers/HMacDSAKCalculator.java#L48

Which is called by bitcoinj here:
https://github.com/bitcoinj/bitcoinj/blob/44ca39bfd7df0068a7aedb1780a8ad954e1cd50c/core/src/main/java/org/bitcoinj/core/ECKey.java#L40

This issue is closed.
