### ISSUE TITLE
issue finalizing master seed backup

### ISSUE THREAD

**Issue by jlopp** [mycelium-com/wallet#143]
I just went through the process of creating a master seed backup using version 2.1.0 on a Motorola Moto X. I got through the word list wizard and when I finished verifying the last word (I had been typing with the phone in landscape orientation) I rotated the phone into portrait orientation.

When the phone was in landscape mode, it was displaying a button to set a PIN code for my wallet. When I flipped to portrait mode, the PIN button disappeared and I was left on the screen showing that I had successfully verified my backup phrase, but there were no actionable buttons and I don't know how to get to the PDF backup. I then backed out of that screen and set a PIN code via the settings but it looks like I won't be able to generate a backup for another 2 days.

**Comment by DanielWeigl** [comment]
Thank you for the bug report - the disappearing dialog after rotating is definitly a bug. We will fix it asap.

But there is no PDF-Export anymore. If you have noted the 12 Words, then you have the full backup. See "BIP39" or "HD Wordlist-Backup"

**Comment by jlopp** [comment]
Gotcha - I figured out that what I wanted was the Legacy Backup since I have both an HD account and a lot of legacy accounts. It might be helpful if you conditionalize a message at the end of the HD backup process that, if the wallet contains legacy accounts, displays a button to take them to the legacy backup wizard.

**Comment by Giszmo** [comment]
should be fixed
