### ISSUE TITLE
Scan HD key derivation paths for other known wallets.

### ISSUE THREAD

**Issue by mcelrath** [mycelium-com/wallet#147]
Not all wallets follow the recommendation of BIP44 for key derivation paths.  In particular, Bread Wallet uses m/0/0'/0/.  This makes it impossible to import keys from such wallets.

Suggested enhancement: Scan the first few keys in the key path for other known wallets, to see if they have coins, when importing a wallet passphrase backup.

**Comment by SimonBelmond** [comment]
I would also like to see this integrated. A friend tired his HD seed from Hive wallet in Mycelium and was at first shocked that the balance was 0.

**Comment by Giszmo** [comment]
Hive master seeds can now also be sweeped.

The problem with non-standards is that there's so many of them. If you have a suggestion how to reasonably implement this in a consistent way, feel free to re-open this issue.
