### ISSUE TITLE
[Feature Request] QR Scan to Also Pull Address Balance In Addition To Allowing Payment

### ISSUE THREAD

**Issue by ajarmonster** [mycelium-com/wallet#149]
I scanned the open issues and didn't see anything, so thought I'd make an issue for this.

The newish camera button on the "Balance" page to allow scanning of QR codes is great, but it would be fantastic if right below the "Recipient Address" on the send page it listed the current balance of the address.

Reason being, it would be very helpful for those of us with paper wallets to quickly scan and verify current balances.

Great wallet by the way, been using it for the last 1.5 years and love it. The new "economic" fee option is very cool.

**Comment by puggan** [comment]
Sounds great, today i have the public keys saved, but if someone steels my phone, they can easy see how mutch I have in offline wallets. With this I don't need to store them in phone, I can just scan there QR when i want to check them.

**Comment by jandreske** [comment]
You can select "cold Storage" from the menu, scan the address and see the balance.

**Comment by ajarmonster** [comment]
@jandreske confirmed that works to check balance. Would still be cool to see balance displayed from the accounts page QR scan button given the much shorter number of steps to get there.

Currently: swipe right to get to get to accounts (1) -> click upper right for menu (2) -> click cold storage (3) -> click 'QR Code' (4) -> Scan QR code (5)
-vs.-
Click camera button (1) -> Scan QR code (2)

**Comment by jandreske** [comment]
You can skip swiping to accounts tab :)

**Comment by DanielWeigl** [comment]
If you scan an address, in most cases your intention is to send money to it and not see how much there is on this address - therefore this is the default action.
