### ISSUE TITLE
[feature request] Traders can define expected time for a trade to happen plus convenient times and places

### ISSUE THREAD

**Issue by SimonBelmond** [mycelium-com/wallet#151]
After playing a bit with the trader feature and completing a few trades I learned that sometimes you have people contacting you getting disappointed because:

* You did not write back immediately
* The next available meeting time or place was inconvenient for them.

I propose to optionally include fields to enter regularly convenient times and places for the trader. So let's say I have two adds up, one for buying and one for selling. The potential other traded could see on both of these adds that I am only available sundy nights at bar xyz plus on Thursdays over lunch at Starbucks xyz. Of course the other trader can contact me usual and we can agree on other places and times.

I would also like to be able to state that you can e.g. expect a deal to go down approx. 1 week after contacting me. Professional traders could state 1-2 days.

These criteria could important for some people. A person who wants to buy 30$ worth just to try it might happily wait for a week. A person who needs to sell in a hurry might want to sells a.s.a.p.

THX for reading

**Comment by Giszmo** [comment]
local trader allows to add a description for all such details. A trading schedule would make sense to dynamically switch the ad on and off but as local trader is meant to work slowly, users would want to get in touch days before the trade.

Anyway thank you for your suggestion. Currently we don't intend to add these extra fields.
