### ISSUE TITLE
Override pasted amount when using numpad to set amount

### ISSUE THREAD

**Issue by marfillaster** [mycelium-com/wallet#152]
Currently, when you paste an amount from clipboard and attempt to override the value using the numpad  doesn't work. The work around is to press cancel and reopen the set amount panel.

**Comment by jandreske** [comment]
You cannot just type to override, as you cannot when you entered an amount manually. This key on the num pad deletes digits which you can then replace: <

**Comment by marfillaster** [comment]
That's actually what I'm trying to do, replace entirely the pasted amount. Sorry for the confusion. And yes, as of latest beta release. Typing in a new value does not replace the pasted amount.

**Comment by johnzweng** [comment]
@marfillaster It's not possible to overwrite the pasted amount, you need to delete the pasted digits before  you can enter new digits by using the "<" key on the numpad. Did you do this or did I misunderstand you?

**Comment by marfillaster** [comment]
My bad. I think i might have skipped pressing that button. Will try next
time. I guess ill close this for now.
