### ISSUE TITLE
Accounts tab locked, but the wallet still shows accounts and balances up after scanning a "bitcoin:..."-schemed QR code

### ISSUE THREAD

**Issue by martinrlie** [mycelium-com/wallet#153]
I'm not sure if the purpose for locking the "ACCOUNTS" tab is documented anywhere, but I've come to see it as a 'privacy' feature, i.e. when the accounts tab is locked, no one will be able to see your accounts - and their balances - without entering the code.

If this assumption is correct, it's unfortunate that the accounts (including names and balances) show up once you scan a QR code starting with the "bitcoin:" scheme. Mycelium happily asks you to "Select Spending Account" and shows what I thought was supposed to be hidden (until it was unlocked by typing the code).

**Comment by jandreske** [comment]
Good catch - we should probably ask for the PIN before allowing to select an account if the tab is locked.

**Comment by Giszmo** [comment]
this is fixed
