### ISSUE TITLE
Can't enter one of the words in my backup restore key

### ISSUE THREAD

**Issue by isaac-bst** [mycelium-com/wallet#154]
I had some bitcoins on my Mycelium wallet on my Nexus 4 device since last October. That device recently broke and I tried to restore my wallet on my new Nexus 5. I had a 12 word backup restore key.

Steps followed:
1. Opened the app and chose "Restore from backup".
2. Chose "12 words" and "no password".
3. I entered the first few words successfully.
4. The next word in my key did not show up as one of the available options, and I was unable to proceed.

For reference, the problematic word was "sheet".

Is this some kind of BIP39 vs BIP44 issue?

**Comment by DanielWeigl** [comment]
Hello, 

"sheet" is not a valid word: https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt - maybe you misread your noted word? "street"? "sweet"?

The wordlist has also a checksum, so you can try to complete it with different words and the app will show you an error after the last word, if the checksum does not match.

**Comment by isaac-bst** [comment]
Did the wordlist change at any point?

And does the app lock you out of your account if you enter an incorrect backup code too many times? I don't want to keep trying different combos only for it to cause my account to be disabled.

**Comment by DanielWeigl** [comment]
No - the wordlist was never changed. And no, the app does not lock you out if you try it too often, so feel free to try :)
