### ISSUE TITLE
Bip70 support?

### ISSUE THREAD

**Issue by tchoulihan** [mycelium-com/wallet#158]
I'm doing some BIP70 testing, with bitcoin uri's like:

bitcoin:mgDpBzcoVZhPaZTYEJqNz8ujWToXSTTJMb?r=http://xx.xx.xx.xx/api/payment_request/4&amount=0.01125923

Mycelium will use and prefer the `r=` parameter, correct?

**Comment by tchoulihan** [comment]
Yep confirmed. I just tested this out and mycelium doesn't have BIP70 support.

It didn't recognize any of my bitcoin: URIs:
https://github.com/bitcoin/bips/blob/master/bip-0072.mediawiki

**Comment by jandreske** [comment]
BIP70 support is added in the current beta and will be available with the next release :)

**Comment by steve-vincent** [comment]
Is this released yet? 
I'm on android Mycelium 2.5.9, and I'm trying Electrum BIP70, described here: http://docs.electrum.org/en/latest/merchant.html
E.g.
https://the-vincents.org/electrum/index.html?id=8afeb76b0c
(using letsecrypt cert)

Mycelium scans then gives error "server responded with wrong mime type" and "invalid signature".
(Coinbase app reads the QR okay however.)

**Comment by DanielWeigl** [comment]
BIP70 is supported - ive never seen electrums implementation of it - will check it later.

But just a quick check showed me, that the response for `https://the-vincents.org/electrum/8afeb76b0c` (the URI for the payment request) is `Content-Type:application/octet-stream`, but according to https://github.com/bitcoin/bips/blob/master/bip-0071.mediawiki needs to be `application/bitcoin-paymentrequest` (thats the error "server responded with wrong mime type" you were getting)
