### ISSUE TITLE
Can't create new account

### ISSUE THREAD

**Issue by disposable-ksa98** [mycelium-com/wallet#160]
When I first installed Mycelium I created an account just to test it, made a few transactions, and then archived it.

Then I created my actual personal account, which I use.

And now I need to create another separate account for a business. But it won't let me: It says I can't have more than 1 unused account.

I need a new account for my business (I don't want to mix it up with the other accounts), please fix this.

Edit: I fixed this doing the following: activate the archived test account, create the new account, archive the test account again. But obviously no one should have to go through this, so this still needs fixing.

**Comment by jandreske** [comment]
There might be a bug concerning archived accounts, could you please try to activate the archived test account and then create a new one? If that works you can archive the test account again afterwards. 

-------- Ursprüngliche Nachricht --------
Von: disposable-ksa98 <notifications@github.com> 
Datum: 20.04.2015  00:20  (GMT+01:00) 
An: mycelium-com/wallet <wallet@noreply.github.com> 
Betreff: [wallet] Can't create new account (#160) 

When I first installed Mycelium I created an account just to test it, and then archived it.

Then I created my actual account, which I use.

And now I need to create another separate account for a business. But it won't let me: It says I can't have more than 1 unused account. Apparently it considers accounts with 0 bits, unused. But it has been used.

I need a new account for my business (I don't want to mix it up with the other accounts), please fix this.

**Comment by Giszmo** [comment]
I assume this is resolved ...
