### ISSUE TITLE
clearly display charged fees

### ISSUE THREAD

**Issue by algazarra** [mycelium-com/wallet#163]
I'm confused, I couldn't check if mycelium charges any fees. I searched both the app and the official website. And finally got here - https://www.reddit.com/r/Bitcoin/comments/2vfn86/mycelium_wallet_was_suspended_from_google_play/

Fee or no fee Mycelium should clearly display this info.

**Comment by DanielWeigl** [comment]
What fees do you mean or expect? We dont charge any fees at all. If you mean the transaction-fee that is the fee that goes to the miner who includes your transaction into the blockchain and is inherent to the bitcoin protocol.

If you you mean our local-trader platform, you would have read that we also don't collect any fees here, if you read the TOS which you have to accept before of the first trade.

**Comment by gjo0117** [comment]
求救 ~ 我現在要如何操作

**Comment by algazarra** [comment]
TY for clarifying. If I recall correctly there used to be a fee. it charged 0.2% (?)
So was there a change due to googleplay?
