### ISSUE TITLE
Paying dialog in offline mode hangs up

### ISSUE THREAD

**Issue by Perlover** [mycelium-com/wallet#165]
Hi,

If i will try to pay and when i enter to pay dialog and in this moment i have offline mode or bad internet link - the Mycelium (v2.3.1) hangs up. I think the main reason of this behaviour - the Mycelium tries to get exchange rates (in my installation i have three measures - USD/RUB/CZK) from internet and waits it in blocking mode. I think by this way because i see ony "mbtc" measure. Some buttons of digit keyboard of the Mycelium are not active of if active - don't respond to clicks.

I think it's not right behaviour because i have read that i can pay by the Mycelium in offline. May be it's true if i scan QR code where is address & sum of payment. But if i have ony a bitcoin address in copy/paste buffer and should enter an sum of payment - i cannot do offline payment :(

**Comment by gjo0117** [comment]
有人可以說中文ㄇ

**Comment by DanielWeigl** [comment]
Thank you for the bug report - I was able to reproduce it and it will be fixed in the next release.
