### ISSUE TITLE
Local Trader: Notification never arrives v2.3.1

### ISSUE THREAD

**Issue by ondra-novak** [mycelium-com/wallet#166]
I saw no notification from the local trader on any device that i used or using now. Never! This doesn't work and i don't believe that it ever worked. Currently, Android 4.0.1, Mycelium v2.3.1 Missed four trades.

Only solution for now is to Disable Local Trader

**Comment by raedah** [comment]
This is a duplicate of https://github.com/mycelium-com/wallet/issues/77

**Comment by DanielWeigl** [comment]
see here: https://github.com/mycelium-com/wallet/issues/77#issuecomment-164679245
