### ISSUE TITLE
Local Trader: Email notification works wierd v2.3.1

### ISSUE THREAD

**Issue by ondra-novak** [mycelium-com/wallet#167]
1. Settings
2. Tap on Use email for notifications
3. Strange popup appear, where just only input line and two buttons "Cancel" and "Ok". What now? It probably needs my email ....
4. Entering my primary email (@seznam.cz). Tap OK, popup disappears and nothing happened.
5. Tap on Use email... again.
6. Again same popup window, but still empty line
7. Entering my secondary email (@gmail.com). Tap OK, popup disappears and the same result (nothing)
8. Next attempt and the line is still empty.

...

After aprox. a hour, an email arrived to my primary e-mail account and notification immediately popped up, about that my e-mail must be verified. No e-mail arrived to my secondary account (gmail.com) yet!

So now I have chance to be informed about the trade one hour after the trade expired. Great improvements (better then nothing, really)

**Comment by ondra-novak** [comment]
Email did not arrived, settings is again empty, trade expired. 

My suggestion is get rid of the local trader it is broken.

**Comment by DanielWeigl** [comment]
Hi,

Thank you for your feedback, I just added some more messages while setting the email address for LT. Will be included in the next release...

The reason why the email-textbox was empty after entering it is, that we only accept the email address after you clicked on the verification link.
But I dont know why the mail took that long to get to you - ive just tested it and it arrived in an instant.

> My suggestion is get rid of the local trader it is broken.
There are clearly some areas we need to improve (if we only had enough time...) but I'm not quite sure, if those kind of problems would justify to dump the whole LT - or?
