### ISSUE TITLE
trezor: outbound tx rejected by network

### ISSUE THREAD

**Issue by molecular** [mycelium-com/wallet#168]
I just tried to send some money from a mycelium trezor account (with passphrase).

I tried 3 times with the same result after broadcast: a popup saying: "The transaction was rejected by the network, this indicates your wallet is out of sync".

I'm pretty sure the wallet isn't out of sync. So far I had only put funds on the first address, this was attempt at the first outgoing tx.

Is there a way to capture a meaningful debug log? With adb logcat maybe? Is there a way to dump the tx?

**Comment by molecular** [comment]
I tried again with a different amount (max) and a different receiving address with the same result.

**Comment by DanielWeigl** [comment]
Hi,

What trezor-mode did you use? Via "Cold-Storage" -> "Sign with Trezor" or an imported Trezor account? In the second case this error arises if you enter a different password while signing the outgoing tx. I hadnt had the time to make a proper check, if the entered password leads to the correct private keys as needed for the account. (The same would currently happen, if you use a different trezor/masterseed to add the account and to sign the transaction)

If you used Cold-Storage, then I dont know how that might lead to this kind of behavior.

**Comment by molecular** [comment]
imported trezor account

you are correct: I used wrong passphrase.

I would assign rather high priority to implementing that check. It can make users feel very uneasy: they will assume (rightly so) they entered the correct passphrase and of course there will be fear of lost coins.

Thanks for an awesome wallet otherwise, I really love mycelium even more now with trezor support.

**Comment by molecular** [comment]
closing this ticket after making a new one for the check: #169
