### ISSUE TITLE
Improve syncing (fastSync branch)

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#170]
I've imported the xpriv from another Mycelium wallet but after 3-5 trades the the other wallet goes out of sync and I need to reload account. Taking as much as 5 min to load the 1500 transactions.

**Comment by jandreske** [comment]
Thanks for the info - just to be sure I got it correctly: You have one mycelium installation, and import one of its HD accounts (native, derived from seed) in a second mycelium installation. You then use that second one to make some transactions (outgoing, incoming or mixed?) and the first, original installation fails to synchronize correctly, not seeing all of these transactions. Is that correct?

**Comment by Transisto** [comment]
Yes, Pretty much. They're mostly outgoing transaction, I haven't tested exactly after how many transaction it happen but it should be more.  I think as little as 3-5. I would expect the refresh button to be able to fix those things.

The first visible symptom are that the balance is reflected as 0.006214 (some small change amount)

**Comment by Transisto** [comment]
This is super annoying, it happen almost on a daily basis.

**Comment by Giszmo** [comment]
For various reasons we are trying to improve the syncing but 1500 transactions sounds like a power user. As an interim solution I suggest you create a new account and archive that large account if that's possible. Archiving excludes it from the balance query, as with an active account that has 1500 private keys, you obviously wouldn't want to miss a single transaction to any of those 1500 addresses and therefore they have to be queried all of them, which makes the request object rather big, the server operation rather expensive and slow or the reply big. All these are aspects we can and will improve on.

**Comment by Giszmo** [comment]
@DanielWeigl is this issue fixed or is there still more fast sync to be done?
