### ISSUE TITLE
Argentinian Peso with WRONG exchange rate

### ISSUE THREAD

**Issue by stupidcache** [mycelium-com/wallet#171]
Hello Every body. The  correct value for argentinian peso is not the official of argentinian central bank, is the exchange rate of th streets. Usually we use this web page, and there is an API in oprder to get the price

www.mercado-bitcoin.com.ar/

Regards!

**Comment by DanielWeigl** [comment]
In the recent version we provide a new rate called XAR, which is based on rates from http://bluelytics.com.ar/ - can you check, if thats a more sane rate for bitcoins in Argentine?

**Comment by stupidcache** [comment]
Thanks!. Now it is far better :)
