### ISSUE TITLE
No Account found

### ISSUE THREAD

**Issue by khizarhayat** [mycelium-com/wallet#172]
I have downloaded this project and run on my android device . When i attached my Trezor with it (testnetmycelium) it is showing No account found rathar than Account list.
But same trezor with mycelium app installed from playstore is showing perfectly. Where i am going wrong is there any configration needed to integrate  trezor with this .
Please help on urgent bases. 
Thanks

**Comment by khizarhayat** [comment]
i found solution 
there are tow files product.xml  in both string name "network" having different value prodnet and testnet
i replaced testnet to prodnet and then its working fine :)

**Comment by jandreske** [comment]
You do not have to modify the product.xml -> there are two versions of the app, the regular one and the testnet version. If you want to use a trezor with real bitcoin accounts, you have to use the regular version of mycelium app. You can use the testnet version of the app with trezor as well - obviuously, testnet mycelium will not find prodnet trezor accounts. There is a mytrezor testnet version as well: https://dev.mytrezor.com/release_4/testcoin/

**Comment by khizarhayat** [comment]
when i ran app it is automaticaly run testnet version how can i ran product version ?

**Comment by DanielWeigl** [comment]
From https://developer.android.com/tools/building/configuring-gradle.html

>To work on files from a particular flavor, click on Build Variants on the left of the IDE window and select the flavor you want to modify in the Build Variants panel, as shown in figure 2. Android Studio may show errors in source files from flavors other than the one selected in the Build Variants panel, but this does not affect the outcome of the build.

**Comment by khizarhayat** [comment]
thanks both of you :)
