### ISSUE TITLE
Support fee bumping in the UI

### ISSUE THREAD

**Issue by btcdrak** [mycelium-com/wallet#173]
[First seen safe replace-by-fee](http://www.mail-archive.com/bitcoin-development%40lists.sourceforge.net/msg07829.html) is now actively mined by f2pool (21% of the network hash) and we can expect more pools to support this soon. The feature allows users to increase the fee of an existing transaction and rebroadcast it. This offers the possibility of significant usability improvements for bitcoin users who send a transaction with an insufficient fee, or at a time when the network is busy confirming spam transactions, can now rebroadcast with a higher fee to bump the priority. No more stuck transactions.

code can be found here: https://github.com/bitcoin/bitcoin/pull/6176

**Comment by Giszmo** [comment]
FSS RBF was replaced by opt-in RBF. I suggest we keep this issue around for anything RBF, as RBF needs to be addressed, especially on the receiving end.

**Comment by Giszmo** [comment]
#186 is related

**Comment by dmp1ce** [comment]
I would really like this.

**Comment by Giszmo** [comment]
I don't see Mycelium sending RBF transactions anytime soon. These should probably remain a thing for bigger entities that have many payouts per block, so they can put all these into one tx.

Can we close this as won't fix?

**Comment by DanielWeigl** [comment]
Yes, i dont think we will be working on that in next few months. CPFP is a lower hanging fruit and might be more approachable
