### ISSUE TITLE
Camera switch (back-front)

### ISSUE THREAD

**Issue by FrancisPouliot** [mycelium-com/wallet#174]
It would be extremely useful for us to be able to switch between front and back cameras of a mobile device to scan qr codes.

We use mycelium as the POS for our physical Bitcoin exchange, Satoshi Counter.

**Comment by Transisto** [comment]
I would really like this too, I used to let the N7 tablet on the table and have the person scan his QR on his own, my new table has a back camera so I can't do this anymore.

Thanks

**Comment by Giszmo** [comment]
Guess there is room for a third button in the scan activity. Will see if we have time for this.

**Comment by Giszmo** [comment]
This issue just got promoted as there seams to be at least one phone (Nexus 5X) that defaults to selfie photos for the QR-Code scanning. Being able to switch would help both groups of users.

**Comment by Giszmo** [comment]
The latest version of zxing [does support picking a camera](https://github.com/slepmog/zxing/blob/master/android/src/com/google/zxing/client/android/CaptureActivity.java#L226), although I understand it does not allow switching and neither remembers the last choice, which would make this improvement somewhat more complicated than it could be if zxing provided it.

**Comment by Giszmo** [comment]
I don't see well how mycelium uses [zxing](https://github.com/zxing/zxing). It seams to be imported as a snapshot at some version around 6/14/13 and then modified (tig shows Daniel Weigl). Not sure how to easily update to the latest zxing version or if anything but some typos in the comments was edited but the version differs a lot from their master.

**Comment by Giszmo** [comment]
Version 2.6.0 allows to switch the camera.

The switch gets stored as default for the next scan, if the scan succeeds.

The binaries are on the play store and the website. @FrancisPouliot and @Transisto please let us know if that solves your issue.
