### ISSUE TITLE
Display Backup location

### ISSUE THREAD

**Issue by Sepero** [mycelium-com/wallet#175]
I backed up my wallet, followed all the steps. Now what? It says a backup was made. Ok, sorry I didn't see where?

Now when I go to Backup, it says I have to wait about 2 days.

Please display the backup location when going to Settings > Backup

Thanks  ;-)

**Comment by mycelium-com** [comment]
If you have noted down the 12 words then you have all you need to recover all your HD-Accounts after a crash or a lost phone.

If you have any suggestions how we should explain it better in the app, please leave us some feedback 

Am 27. Juni 2015 10:44:34 MESZ, schrieb Sepero <notifications@github.com>:
>I backed up my wallet, followed all the steps. Now what? It says a
>backup was made. Ok, sorry I didn't see where?
>
>Now when I go to Backup, it says I have to wait about 2 days.
>
>Please display the backup location when going to Settings > Backup
>
>Thanks  ;-)
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mycelium-com/wallet/issues/175

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Sepero** [comment]
I have the 12 words noted down. I read something in the documentation about a PDF document being created? Am I able to restore my wallet on any device with only the 12 words? Does using this 12 word restore contact mycelium servers to restore my wallet?

**Comment by jandreske** [comment]
The .pdf file backup is the old way of making a backup, and it is still required to back up single key accounts and watch only addresses. All accounts derived from your master seed are backed up by only the 12 words. No contact to the mycelium servers needed, there is nothing stored somewhere else, it is really only those twelve words. This procedure is according to a standard, BIP39 (and the created account structure is BIP44) and you can restore your accounts in any compliant wallet like trezor, wallet32 or multibit HD.

**Comment by Sepero** [comment]
Ok, that's great to know, and that is the answer I needed to be confident in transitioning my wallet to mycelium. For the benefit of others, you may want to add this information to the MyCelium FAQ.
https://www.mycelium.com/wallet/FAQ.html

Thank you very much for taking the time to clear this up for me. :-)

**Comment by Sepero** [comment]
I may also suggest highlighting this information on the screen Backup menus. :-)
