### ISSUE TITLE
Interface with Pebble Time smartwatch

### ISSUE THREAD

**Issue by fdemmer** [mycelium-com/wallet#176]
This is a feature request.

It would be great to have Mycelium send QRs of my wallet to the Pebble so people can directly scan my watch to send coins.

Other useful feature would be showing balance of wallets and transaction status...

**Comment by Transisto** [comment]
This would require development of a pebble app. I currently use a QR code display app on my pebble and just copy one of the public key on it.

What would be the point of requesting the mycelium app send to the watch when you actually have the phone your hands ?

**Comment by Giszmo** [comment]
Mycelium uses BIP44, so you can export an account's xpub key and use it in a pebble watch app to receive payments to the account without adding the pebble overhead to Mycelium itself. We would be happy to see such a tool but currently won't work on that ourselves.

(I have ... actually two pebble watches and a Sony Smartwatch 2 but would assume that the first smart watch to get such a feature from our side would be an android wear watch and not some smaller market. But third party contributions are welcome.)
