### ISSUE TITLE
Notification when receiving bitcoins

### ISSUE THREAD

**Issue by bramp** [mycelium-com/wallet#18]
It would be good if the app could pop up when I receive money.

Mining pools pay me randomly so I'd like to know.

**Comment by Giszmo** [comment]
This would mean that a central server would have to know your google ID being interested in those addresses or your phone would have to regularly poll which addresses you are interested in.

We have considered options for this but so far always decided to not implement them. Sorry.

**Comment by bramp** [comment]
unhappy face, but understood. Thanks.

**Comment by haight6716** [comment]
How about poll evey x minutes while on WiFi/always?
