### ISSUE TITLE
Send change to "another account"

### ISSUE THREAD

**Issue by fosterman** [mycelium-com/wallet#180]
Right now, if you import a private key and spend from it, it will send the change back to the original address. It would be great if you could send the change to another "account", ideally a freshly generated key on an HD account.

**Comment by jandreske** [comment]
Just send everything from that key to the HD account, then make a transaction from the HD account?

**Comment by fosterman** [comment]
One of the things I liked about Mycelium (vs say Airbitz) is because I don't want to sweep the imported keys until I'm ready to spend them. That may be easier for people but I like more control over my keys.

**Comment by DanielWeigl** [comment]
Okay, that seems to be a good idea, we'll think about it and see if we can implement it in a safe manner so that users surely understand what they are sending where.

**Comment by Rassah** [comment]
If it's just different address for change that you want, you can also use HD xpriv keys instead of plain private keys. It'll generate a new address to send change to just like with any other HD wallet.

**Comment by Giszmo** [comment]
I tend to close this, as it's about deprecated single key accounts? With paper wallet spending I see a potential need to send the change to either the same key or the HD wallet's key but also paper wallets could/should work with `xpriv`? @DanielWeigl?

**Comment by DanielWeigl** [comment]
Yes, its now possible to have an xPriv/xPub paperwallet (just like Entropy generates it) - its a bit slower to cold-spend from it (as it needs to scan more addresses), but way more better for privacy
