### ISSUE TITLE
Where to report server issues?

### ISSUE THREAD

**Issue by kilorat** [mycelium-com/wallet#182]
Obviously posting on github "issues" for the wallet source code isn't the right place.
Right now I'm getting "no server connection", and networking is working from the device.
I read https://github.com/mycelium-com/wallet/issues/62 and there were 2 URLs posted, I get a 404 on the first one, and a gateway error on the 2nd.
https://mws1.mycelium.com/mws/api/1/request/status
https://mws2.mycelium.com/mws/api/1/request/status

My main question is, is there a proper place to check for other people talking about it, like a forum, twitter, irc chat, anything? There's no tweets about this outage on https://twitter.com/myceliumcom

update: I posted to twitter and the response was I should restart the app so it uses another server. That didn't help.

**Comment by threejs123** [comment]
I am having the same issue.  It is telling me the server is down and that my transaction was declined because my wallet is out of sync.  Now my btc is locked up in purgatory.  Jesus H Christ, one f'ing problem after another.

**Comment by threejs123** [comment]
Keep me updated Kilorat.

**Comment by kilorat** [comment]
I got some nice person responding to me on twitter, but they went dark. That's as far as I got.
https://twitter.com/kilorat/status/621094195483119617
I am not sure if they realize how severe this is. If I could just import my HD wallet's seed into another program, I'd at least be able to get access to my bitcoins, but I made another issue for that https://github.com/mycelium-com/wallet/issues/183

**Comment by threejs123** [comment]
I am glad I became aware of the dev's incompetence now while only having a minimal amount of btc in mycelium.  If I ever find a way to get it out you can be damned sure I won't be using mycelium.  It's a good time to get out of dodge.  Unreal

**Comment by kilorat** [comment]
I stumbled on a reddit post about this issue. It would be so nice if there was some official communication channel from these guys so we don't have to go hunting for random posts around the internet during major outages.

https://www.reddit.com/r/Bitcoin/comments/3db7qr/mycelium_servers_down/

**Comment by DanielWeigl** [comment]
@threejs123 you got lucky, you can now move your funds now to a different wallet, the servers are up and running again. They are still a bit slow, as they have to fill up their mempool again. Additionally we also ordered a new, bigger server to speed up our backend

@kilorat, yes this is the correct place to report that issues, sorry that we didnt respond earlier, we were quite busy, fixing the backend stuff.

**Comment by threejs123** [comment]
Thank you for the update.  I overreacted.  It looks like the bitcoin network is overloaded with spam right now, so no, that is not the wallet's fault.  And yes mycelium is up and running now and I will continue to use the wallet.  I have been using it for over a year and this has been the only hiccup thus far.  Thank you.

**Comment by SilkySmooth** [comment]
Any plans to allow users to run their own servers? Mycelium has been a joy to use thus far, but I can't in good conscience continue to recommend it to new users with only 3 (apparently overloaded) servers on the backend. Dealing with panicked calls from newbies due to such issues is not my idea of a good time.

**Comment by Perlover** [comment]
+1
Now i see regulary server problems as i think - i don't see mempool transaction
If i get a bitcoins i can see theirs through blockchain.info but Mycelium doesn't show to me until they have already 1-2 confirmations
I don't know - may be it post-effects of last bitcoin's spam attack (your servers cannot work fast as before) or may be your UTXO DB index works very slowly and may be my BIP44 account has many addresses for watching (171 private keys now) and your servers cannot watch all 171 keys... But it starts to irritate :(

**Comment by Perlover** [comment]
Now everything fine works!
But now no such spam transactions in bitcoin network...

**Comment by Christian1998** [comment]
!Close
