### ISSUE TITLE
Can the master seed on HD accounts be used by other wallets?

### ISSUE THREAD

**Issue by kilorat** [mycelium-com/wallet#183]
Right now I can't use Mycelium because for whatever reasons the servers are down or inaccessible to me, can I get at my bitcoins? I have the seed, but it doesn't seem compatible with other wallets that I have tried.  I really like this wallet, but if my coins are held hostage when there's a server outage, I can't use it. I can't even work around the issues on my own since there's no desktop wallet that can import the seed.
If there's a forum around Mycelum that I can use instead, please point me at it so I don't suck up developer time for things like this, thanks!

**Comment by ticoombs** [comment]
Master seed is BIP44 based. So any wallet that is compatible can be used. EG: MultibitHD

**Comment by sironitomas** [comment]
Would it work with Copay wallet?

**Comment by Rassah** [comment]
It can be used by any wallet that is BIP32, BIP39, and BIP44 compatible. Trezor, MultibitHD, and supposedly Coinomi should be able to import it fine. Possibly others.

**Comment by michaesc** [comment]
That Mycelium can import standard wallets seems to not be true. I'm not sure which BIP standard Electrum uses when generating the 12 word seed, but after typing the words into Mycelium 'restore wallet' feature I always receive a 'checksum invalid' error message. If I type the same words into Electrum the wallet is imported successfuly, however when typing in Mycelium generated seed words in Electrum they are not.

Mycelium: 2.9.4 (290403), Android
Electrum: 2.9.3, Linux desktop, Android

**Comment by Giszmo** [comment]
Mycelium is BIP [39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) and [44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) compliant. Electrum follows its own standard.

**Comment by michaesc** [comment]
Thanks for clarifying that @Giszmo, very good to hear that Mycelium sticks to standards.

**Comment by axelpale** [comment]
DANGER: Master seed might only import single Mycelium account. I had two HD accounts in my Mycelium wallet and imported the seed into Electrum Cash, to claim some Bitcoin Cash. However, only one of two accounts was imported. I had to separately export the private key (with the xprv prefix) of the second Mycelium HD account into separate Electrum Cash wallet to claim everything. Thus, if you have multiple accounts in your Mycelium wallet and want to use them in another wallet, it is better to import with private keys than with the mnemonic master seed.
