### ISSUE TITLE
Add option to default 'Enter Amount' screen to local currency

### ISSUE THREAD

**Issue by Klakurka** [mycelium-com/wallet#184]
Under 'Settings', allow users to decide whether or not to default their amount entered to be in either BTC or one of their chosen local currencies.

What makes this more of an issue is that, currently, there is an odd bug/feature that requires you to press the currency toggle (top right button) twice when trying to switch from (for example) CAD to BTC denominations (the first tap simply displays the amount in CAD... whereas it should be visible at all times anyway I imagine).

Let me know if you need additional clarity on any of these points.

**Comment by Klakurka** [comment]
FYI The issue I outlined in the 2nd paragraph has been fixed.

**Comment by Klakurka** [comment]
It turns out they the second issue is in fact will present.

**Comment by Klakurka** [comment]
*still

**Comment by DanielWeigl** [comment]
Both issues are fixed in the latest version
