### ISSUE TITLE
Feature for Trezor - "to show address in Trezor"

### ISSUE THREAD

**Issue by Perlover** [mycelium-com/wallet#185]
Hi!

Thanks for nice wallet software!
I asked you in email about this feature - to show incoming bitcoin address for Trezor's account in Trezor's screen. You answered that it's planned. But new version was already made but this feature is not realized.

The Bitcoin Trezor has a new secury feature - to control bitcoin address in its screen. If to use Mycelium for getting enough bitcoin amounts a user will want to be sure that incoming address is correct and not be fished. The Electrum or MyTrezor.com show address in Trezor by request.

Can you add this feature near time?

Thanks!

**Comment by Giszmo** [comment]
Only have a keepkey and that shows addresses. I suppose this issue is resolved? Please re-open if not.
