### ISSUE TITLE
Optional transaction delay

### ISSUE THREAD

**Issue by FrancisPouliot** [mycelium-com/wallet#188]
Enhancement proposal: an optional delay before a transaction is broadcast.

For people like us who are doing 100+ transactions a day using Mycelium, it sometimes happens that we make mistakes and send bitcoins to the wrong. Usually we figure this out quite quickly. To prevent this, there could be an optional and customizable time delay (e.g. 5 mins). The transaction is not broadcast until x minutes after the transaction is confirmed via PIN. During those 5 minutes, users can choose to cancel transaction.

**Comment by Giszmo** [comment]
I was thinking about a related enhancement that you might also like if you do hundreds of non-urgent transactions per day: Transaction stashing. I'm thinking about the interface to do multi-recipient transactions and not liking your timeout idea gave me another idea:

If you do low priority transactions every other minute, you might also be annoyed by having to punch in the pin all the time, maybe even in presence of other people.

To fix excessive pin entry, unwanted transaction broadcast and unnecessary chaining with its size overhead we could add a `stash` button next to the `send` button. This `stash` button could store the transaction for later broadcast. Later, if you hit `send` with or without filling out yet another transaction, you would get a list of recipient/amount pairs to confirm and broadcast in one go.

**Comment by Giszmo** [comment]
With #350 this will all be obsolete. Being able to cancel a transaction until it was mined might be enough most of the time for you @FrancisPouliot
