### ISSUE TITLE
transaction selection mostly broken unless local currency selected

### ISSUE THREAD

**Issue by dooglus** [mycelium-com/wallet#190]
I have "No fiat currency selected" in the settings. This causes the transaction pane to be more compact vertically, since only one amount is shown per transaction rather than two.

Unfortunately when I do this it is very hard to select a transaction in the transaction pane. If I have selected a fiat currency I can simply touch any transaction to get the top row to say "done | set label | show details". But with no currency selected, touching a transaction almost always does nothing, occasionally makes the transaction flicker, and very rarely selects it. It is quicker for me to go to the settings, select a fiat currency, select the transaction, operate on it, go back to the settings and unselect the fiat currency.

**Comment by mycelium-com** [comment]
Hello Chris,

We have found the problem that caused this and it has been fixed.
The problem should disappear in one of the upcoming versions.

Greetings,

Constantin
