### ISSUE TITLE
Ledger wallet PIN only supports four digits.

### ISSUE THREAD

**Issue by skorokithakis** [mycelium-com/wallet#191]
My Ledger (well, HW1) wallet PIN is longer than four digits, which makes the app fail. Can we get support for arbitrarily long PINs?

**Comment by DanielWeigl** [comment]
Good point - will be included in the next update

**Comment by Giszmo** [comment]
@DanielWeigl please close if fixed. Can't verify.

**Comment by DanielWeigl** [comment]
Is fixed
