### ISSUE TITLE
Unable to recover wallet after phone factory reset

### ISSUE THREAD

**Issue by rebroad** [mycelium-com/wallet#193]
Hi. My phone got into a reboot loop, so I had to wipe the data on it and restore from backup. I used a number of backup solutions, Helium Backup, BackupYourMobile. All of the backups were done and saved to external SD card.

I have so far been unable to restore my wallet from either of these backups, whereas the other applications have restored fine.

Is this intentional or a bug? (By the way, it's about 8 BTC at stake here).

**Comment by mycelium-com** [comment]
Hi Broadley,

Yes, our app is marked as "do not backup" - as we often got reports of stolen/leaked backups from bitcoin apps which led to financial loss. 
Many apps have access to SDCard, so its very easy to get access to backups lying around on them.

Therefore our app features the 12-word backup - which you hopefully have written down somewhere? You can then recover all your funds from these 12 words.
Just start the app, and on a fresh install it will ask you for the 12 words.

Daniel


Am 2015-09-18 um 11:51 schrieb R E Broadley:

**Comment by rebroad** [comment]
Thanks Daniel. No, i did not use the backup option within Mycelium as I had
backed up the entire phone, or so I thought.

Very disappointed that this is not made clearer.

Who can I apply to for reimbursement of my lost bitcoin please?

**Comment by rebroad** [comment]
Daniel,

So, where is the data to restore the wallet kept please? How is it that
backup software is able to miss this data?

**Comment by DanielWeigl** [comment]
> So, where is the data to restore the wallet kept please?
You can try to find the file "walletbacking.db" - this is where mycelium keeps its masterseed

> How is it that backup software is able to miss this data?
Android provides the option for each app to be exempt from backups. Mycelium has set this option for reasons stated above.

**Comment by rebroad** [comment]
@DanielWeigl If Mycelium has intentionally excluded itself from being backup up, then this is something that needs to be made very clear to the user, IMHO. I'd mark this as an urgent feature, especially considering the financial implications of this not being made clear.

**Comment by johnzweng** [comment]
@rebroad IMHO Mycelium does already make this clear by displaying the label "Missing Backup" along with each account or key which has not been backuped yet.

Including it into the backup feature of Android would make any wallet much less secure, as backups can be much easier accessed than the protected application data. In fact you would weaken the security if allowing adb backups.
