### ISSUE TITLE
Somehow I did a doublespend

### ISSUE THREAD

**Issue by kilorat** [mycelium-com/wallet#197]
I sent some BTC to someone with Mycelium wallet, and his wallet showed twice the value that I sent him. He held up his QR code and I just sent it normally, I'm not aware of anything weird I did to trigger the doublespend. Luckily I didn't enough BTC in my wallet for the amount, so the 2nd one got rejected. I didn't see the 2nd tx in my transaction history until I looked at it an hour later.

Here's the tx that made it:
https://blockchain.info/tx/c953d4fa3a39bcbd77a5835d6d79b5b1765108115ac2cc7963c9dea706016583

Here's the one that didn't get confirmed
https://blockchain.info/tx/348bed197cb52cbc38bcd7515014f36a955ab1b38280ff0799ee958365046d98

I sent another transaction as a test from the same wallet, and no doublespend that time.

Screenshots, in case it helps: http://imgur.com/a/wXFQb

**Comment by DanielWeigl** [comment]
The second transaction is the exact same transaction, but with modified signature values (malleable problem of transactions).

It seems currently someone in the bitcoin network is generating "malleted" transactions. He/She can not steal funds by it, but might cause some confusions, as the transaction ID can not be trusted, until its first confirmations.

See here: http://blog.coinkite.com/post/130318407326/ongoing-bitcoin-malleability-attack-low-s-high#
You can delete the unconfirmed tx from your tx history

**Comment by Michail1** [comment]
Daniel - Thanks.   Noticed several people complaining about such transaction (various wallets), but got the same thing last night myself.  Nearly freaked out - took phone offline.  Looked at history to see it was mall attack and both tx were save inputs.  Brought phone back online and saw the status changed from sending to 'not broadcasted'.  I was then able to delete the unconfirmed tx.  All good again.

**Comment by dmp1ce** [comment]
The same thing is happening to me. I was wondering what was wrong with the wallet. I guess it has nothing to do with the Mycelium wallet. I cannot figure out how to delete the unconfirmed transaction.

How do you delete transactions?

**Comment by Michail1** [comment]
Open your wallet, go to the account with the issue, click on transactions, click on the specific transaction, then settings, then delete it.

**Comment by dmp1ce** [comment]
Thanks Michail1. I think only transactions that allow for rebroadcast can be canceled though. Transactions with only 0 confirmations cannot be cancelled.

**Comment by Michail1** [comment]
Probably so.  What happened for me was that the TX would switch from 0 conf to not broadcasted.  sync and would go back to 0 conf.  I had rebooted the phone and went back to not broadcasted again.  At this time is when I was able to delete it.
(Just prior to being able to delete, I was going to wipe the app/data and restore from backup to see if this solved the problem, but I didn't need to as the delete option was there.

**Comment by kilorat** [comment]
Regarding resorting to wiping app data, something to try before that is to select the account on the accounts screen, then do "Reload account".

**Comment by Giszmo** [comment]
@DanielWeigl I'm pretty sure the malleability issue is fixed? Do sent transactions that are invalid still show in the history? Close?

**Comment by DanielWeigl** [comment]
The handling of doublespends/malled tx is somewhat improved - but there is still room for further improvements, like how to handle added labels to tx's that got rejected and its malled tx got mined, etc
