### ISSUE TITLE
Allow in-app input of cold storage wallets

### ISSUE THREAD

**Issue by janschejbal** [mycelium-com/wallet#199]
The cold storage menu accepts private keys, master seeds, and xpriv keys only from QR codes and the clipboard. As a result, users who have a printed seed/key without a QR code are forced to put it onto the clipboard, which is dangerous (I'm surprised Mycelium even offers that option).

Can we please add a way to input this directly into the app, at least for master seeds (just using the already present input code)? This would also partially mitigate the lack of support for multiple HD wallets.

**Comment by DanielWeigl** [comment]
It is now already possible to enter masterseeds in cold-storage
