### ISSUE TITLE
Allow grouping or tagging of addresses

### ISSUE THREAD

**Issue by zagaberoo** [mycelium-com/wallet#2]
Tagging addresses would make for an extremely powerful key management system without adding any inherent complexity.

An individual could have 'personal' and 'business' tags, and the business tag could have child tags like 'art sales' and 'freelance payments'.

I realize this is a pretty broad and far-out request; really I'm looking to see if this is the kind of feature you'd accept.  If so I'd work on it myself.

**Comment by Giszmo** [comment]
A lot has changed and you can label transactions and addresses, together with multiple accounts etc.

Feel free to re-open if you see it still lacking for your needs.

**Comment by zagaberoo** [comment]
Mycelium definitely meets my needs nowadays; thanks for considering my original request!
