### ISSUE TITLE
Allow multiple separate HD wallets (seeds)

### ISSUE THREAD

**Issue by janschejbal** [mycelium-com/wallet#203]
This has been discussed in #121 but I couldn't find an explicit request tracking it. 

There are use cases where a user might want to use separate HD wallets, e.g.:

* Fully testing a backup/cold wallet by sending money to and from it
* Wanting to have wallets under separate keys
 * shared wallet- A and B each have a personal wallet, and a third one is shared by both
 * separate wallets under a separate passphrase 

I thought simply providing a safe way to use HD seeds with the cold-wallet storage feature (#199) would cover most use cases (testing and cold wallets), but it doesn't allow showing addresses to receive money with. Allowing full use of temporarily-imported wallets, ideally while allowing users to switch between the hot and cold wallet, would probably cover what most users who want this feature need in a more secure way.

The ideal implementation would allow:
 * more than one HD wallet (seed)
 * adding accounts temporarily (i.e. only in memory) but allowing their full use
 * storing seeds without storing the passphrase (creating an in-memory account once the passphrase is entered)

Mycelium already supports xPriv accounts, so I don't think adding this as an advanced feature would make Mycelim too complicated to use. For clarity, the UI for switching between seeds could be separate from the account UI and initially only accessible through the Advanced menu.

**Comment by DanielWeigl** [comment]
The current release (2.5.5 - now in beta) allows to spend from a masterseed via "Offline spending" - it additionally also scans for a Bip32 account (like Hive Wallet uses).

This allows the user to sweep the full amount (or partial, if needed) from external seeds. That enables lot of the use-cases you mentioned, without any big changes to the UI/UX.

**Comment by ikilled** [comment]
I vote for this proposal.
(Mainly the ability to have multiple HD _Wallets_ (not just accounts) - each with different master seed.)

**Comment by rebroad** [comment]
I also vote for this proposal - offline spending is close, but not what is wanted.
