### ISSUE TITLE
Transaction rejected message when transaction was not rejected

### ISSUE THREAD

**Issue by fracas** [mycelium-com/wallet#204]
A few days ago I submitted a transaction and got the error message:
"The transaction was rejected by the network. This indicates that your wallet is out of sync".

Refreshing or restarting the Mycelium app didn't help.
I tried again to submit the transaction several times and always received the same error.

I then waited for about 30 minutes and restarted the phone before trying again.
When I opened the wallet though, I checked the transaction history and I noticed that the transaction that had failed before had been already transmitted and confirmed by the network.

After that the app was working normally again.

If I didn't check the transaction history I would have re-submitted the transaction and effectively I would have paid twice.

I would expect that if the app gives the error message above then the transaction is actually cancelled and not transmitted to the network.

I am using the Android client v 2.5.2.

To add a bit of information:
- The transaction I was trying to submit was using unconfirmed funds, I had done that before and it did not create issues
- The transaction was the first one I was submitting after the malleability attack during the weekend 4/10. During the attack I had noticed two duplicate transactions that appeared in the transaction history. These 2 transactions kept unsuccessfully re-transmitting for a couple of days before they eventually were removed from the transaction history without any effect on my balance. This is probably the cause for the wallet being out of sync.

**Comment by johnzweng** [comment]
ACK, experiencing the same issues right now.

Usecase:
Sweep cold wallet to HD account on mycelium using "cold storage" feature und scanning privkey (this works), a few seconds later send half of the amount to a new (unused) cold wallet (this gives me the error "The transaction was rejected by the network. This indicates that your wallet is out of sync"). Did this a few times in the past but doesn't work today.

**Comment by DanielWeigl** [comment]
@johnzweng, were there unconfirmed outputs on that paperwallet? if the error does still persist, would you care to share the pub key with us (send it to Daniel.Weigl@mycelium.com) - but only if your privacy allows it, of course.

**Comment by DanielWeigl** [comment]
Afair, I introduced a server side bug back then regarding the handling of unconfirmed inputs that would lead to that error message. Is fixed in the meantime.

Regarding the rejected-but-later-sent-tx: The wallet saves locally all tx and tries to broadcast them until either it got confirmed or the user decides to delete it (only possible, as long as the tx isnt confirmed). Maybe we should improve the warning text.

e.g.:
"The transaction was rejected by the network. This indicates that your wallet is out of sync. We will try to broadcast it later"

**Comment by Giszmo** [comment]
I would close this for now and if it happens again you open it again? Or is there anything we can fix now pro-actively?

**Comment by fracas** [comment]
Ok for me. Thanks!
