### ISSUE TITLE
Major PITA  "The transaction was rejected by the network, This indicates that you wallet is out of sync"

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#206]
Mycelium has become almost impossible to use for our business. 

It took us a while to figure out that this misleading message mean we are trying to spend unconfirmed output. Although the wallet allow for sending unconfirmed funds o_0,  When they're part of a transaction made by the wallet this message show up.

We now fund the wallets in multiple small transaction to avoid this problem.

Also the feature that was supposed to allow for better syncing of wallets among two devices does not work at all, look worst than before.

Seems like there is no way to trust anything the wallet is showing as available balance these days.

The week just before we had a slew of double spending that stayed for days in our history.

Is there a Mycelium forum, a Reddit or somewhere people like me can go to get updates, help each others and vent out from time to time ?

**Comment by DanielWeigl** [comment]
Hi,

i now implemented a rule on our backend to not send non-confirmed, non-Bip62-valid transactions to the client. That should solve the troubles causing the current slew of doublespends. (You might need to reload you account, if you have still some unconfirmed tx showing up in your app)

> Is there a Mycelium forum, a Reddit or somewhere people like me can go to get updates, help each others and vent out from time to time ?

I suggest you vent somewhere, where we also see it, then it helps you (and others) the most - so here or at info@mycelium.com

Sorry for the inconveniences

**Comment by FrancisPouliot** [comment]
I don't have any issues to report, seems like problems were fixed. @Transisto ?

Maybe issue can be closed?

**Comment by Giszmo** [comment]
closing. feel free to re-open.
