### ISSUE TITLE
option to encrypt wallet on device

### ISSUE THREAD

**Issue by jdchristensen** [mycelium-com/wallet#21]
Is there documentation explaining how the wallet is encrypted on the device?  I'd like to know a bit more about how secure this is.  Is the encryption key based on the pin?  Is there anything to prevent someone who gains access to the encrypted data from trying all 6 digit pins quickly?

**Comment by Giszmo** [comment]
Old issue with a valid concern that was excessively addressed time and again with the solution we currently have for the reasons described above. I guess it's ok to close it.

**Comment by thousandsofthem** [comment]
okay, sure. still, i think encryption is much superior than everything else in terms of security. way too easy to steal private keys
