### ISSUE TITLE
Local trader unable to connect to hidden service

### ISSUE THREAD

**Issue by dmp1ce** [mycelium-com/wallet#211]
I'm trying to view my messages on local trader using Tor but the messages never update. Mycelium eventually says "no server connection" but the Tor icon at the top of my phone appears to still be working.

On Orbot it says "Notice: Closing stream for '[scrubbed].onion': hidden service is unavailable (try again later)."

Is there a problem with the hidden service for the local trader?

My price and transactions seem to be updating fine.

**Comment by dmp1ce** [comment]
My ads are also not showing up.

**Comment by DanielWeigl** [comment]
Yes, tor endpoint for localtrader got stuck - is now up again

**Comment by dmp1ce** [comment]
Thanks! It is working now.

**Comment by dmp1ce** [comment]
This is happening again for the wallet onion I think. I sent a support ticket on Zendesk yesterday but nobody responded.

**Comment by Giszmo** [comment]
serever was down. sorry.

**Comment by dmp1ce** [comment]
No problem. Is there a status page somewhere? What is the best way to notify you guys if the server goes down? Am I think only one use the .onion servers? lol.

**Comment by Giszmo** [comment]
My rule of thumb is that if one person reports something, about 100 are affected.

We should have that covered by our monitoring and we should have the redundancy working. I'm rather new to the team and don't know why the other server running doesn't rescue the day but I will find out. We would love to see all people use tor but as it's slightly more complicated than not using it, it's not going to happen magically. But maybe we can make it default on the rewrite.

**Comment by dmp1ce** [comment]
Well, I think it is a great feature. I hope it doesn't take too much resources on your end. I always use Tor to send transactions.

**Comment by dmp1ce** [comment]
Is the Tor service down? My transactions are not updating.

**Comment by DanielWeigl** [comment]
Yes - seems our tornode on the LT backend got stuck... is working now again

**Comment by dmp1ce** [comment]
I'm still not able to get updated transaction information through Tor.

**Comment by DanielWeigl** [comment]
What do you mean by that? is the transaction confirmation bar stuck? if so, can you mail us your txid? info@mycelium.com - thx

**Comment by dmp1ce** [comment]
It is working now. Just after I posted transactions started to update. Thanks.

**Comment by dmp1ce** [comment]
I'm again having trouble connecting using Tor. I created a support ticket yesterday on zendesk but I haven't gotten a response yet.

**Comment by Giszmo** [comment]
Ok, so we have some [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug) here. When somebody claims to have issues with our TOR services, I run:

    $ for i in slacef5ylu6op7zc n76y5k3le2zi73bw vtuao7psnrsot4tb rztvro6qgydmujfv;
          do echo $i;
          curl -v --socks5-hostname localhost:9050  -m4 -s -k -X POST -H "Content-Type: application/json" https://{$i}.onion/wapi/wapi/getMinerFeeEstimations ;
          done

and sometimes I get no reply on the four urls. The first and the last are the same server. Running it again I then might get 4 perfect replies and if I try ten minutes later it works again or maybe not or maybe for 3 out of 4 requests. Not sure why it fails.

Here are two example outputs for the same server:

It's equal for the first part:

````
slacef5ylu6op7zc
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 9050 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 9050 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
````

When it fails, it ends in these two lines:

````
* Operation timed out after 0 milliseconds with 0 out of 0 bytes received
* Closing connection 0
````

(Ok, after writing all that's below I found the 0ms is [just a reporting issue](https://github.com/curl/curl/issues/619) while it actually does time out. But why it times out remains unclear. The server is idling at <1% CPU, spiking to 5% for a second at times … ok and then sometimes CPU spikes to 50% but without my test script failing at all during sustained load for 10s.)

and when it works:

````
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: OU=Domain Control Validated; OU=PositiveSSL Wildcard; CN=*.mycelium.com
* 	 start date: 2013-06-12 00:00:00 GMT
* 	 expire date: 2014-06-12 23:59:59 GMT
* 	 issuer: C=GB; ST=Greater Manchester; L=Salford; O=COMODO CA Limited; CN=PositiveSSL CA 2
* 	 SSL certificate verify result: certificate has expired (10), continuing anyway.
> POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1
> User-Agent: curl/7.38.0
> Host: rztvro6qgydmujfv.onion
> Accept: */*
> Content-Type: application/json
> 
< HTTP/1.1 200 OK
* Server nginx/1.6.3 is not blacklisted
< Server: nginx/1.6.3
< Date: Mon, 30 May 2016 20:59:08 GMT
< Content-Type: application/json
< Content-Length: 180
< Connection: keep-alive
< 
* Connection #0 to host rztvro6qgydmujfv.onion left intact
{"errorCode":0,"r":{"feeEstimation":{"feeForNBlocks":{"1":"61665","2":"39837","3":"31715","4":"23787","20":"9242","5":"19340","10":"13342","15":"11011"},"validFor":1464641923380}}}
````

On the server I can't find anything neither. TOR itself is not logging any errors. debug.log is empty and notices.log reports once every some hours how productive tor is. According to the tor config, notices.log would contain warnings and errors if there were any.

The nginx log reports are not revealing much.
error.log has the typical probing for open phpmyadmins.
access.log grepped for feeEstimation:

    [30/May/2016:23:43:03 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "curl/7.38.0" "-"
    [30/May/2016:23:43:06 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "curl/7.38.0" "-"
    [30/May/2016:23:43:08 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "curl/7.38.0" "-"
    [30/May/2016:23:43:11 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "curl/7.38.0" "-"
    [30/May/2016:23:43:14 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "curl/7.38.0" "-"
    [30/May/2016:23:43:16 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "curl/7.38.0" "-"
    [30/May/2016:23:43:19 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "curl/7.38.0" "-"
    [30/May/2016:23:43:22 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "curl/7.38.0" "-"
    [30/May/2016:23:43:24 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "curl/7.38.0" "-"
    [30/May/2016:23:43:32 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "curl/7.38.0" "-"
    [30/May/2016:23:43:36 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "curl/7.38.0" "-"
    [30/May/2016:23:43:39 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "curl/7.38.0" "-"
    [30/May/2016:23:44:56 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "okhttp/2.7.4" "-"
    [30/May/2016:23:46:23 +0200] "POST /wapi/wapi/getMinerFeeEstimations HTTP/1.1" 200 180 "-" "okhttp/2.2.0" "-"

Agent=curl must be my script from above. The server has a time offset, with some log files logging some hours off again but the minutes and seconds are accurate:

    $ ssh node7 date; date
    Tue May 31 00:43:14 CEST 2016
    Mon May 30 18:43:14 CLT 2016

Ok, I slightly modified above script for this:
    $ for i in $( seq 1 100 ); do echo $i; date; curl -v --socks5-hostname localhost:9050  -m4 -s -k -X POST -H "Content-Type: application/json" https://slacef5ylu6op7zc.onion/wapi/wapi/getMinerFeeEstimations 2>1 ; done

Its output around the error happening:

    90
    Mon May 30 17:43:22 CLT 2016
    {"errorCode":0,"r":{"feeEstimation":{"feeForNBlocks":{"1"…
    91
    Mon May 30 17:43:24 CLT 2016
    92
    Mon May 30 17:43:28 CLT 2016
    93
    Mon May 30 17:43:32 CLT 2016
    94
    Mon May 30 17:43:36 CLT 2016
    {"errorCode":0,"r":{"feeEstimation":{"feeForNBlocks":{"1"…


Matching this with the server log looks strange:

    43:22
      nginx reports getMinerFeeEstimations 200 by curl
      succeeding query is started
    43:24
      nginx reports getMinerFeeEstimations 200 by curl
      failing query is started
      failing query is started
    43:32
      nginx reports getMinerFeeEstimations 200 by curl
      failing query is started
    43:36
      nginx reports getMinerFeeEstimations 200 by curl
      succeeding query is started
    43:39
      nginx reports getMinerFeeEstimations 200 by curl for the last time
      (query is started and process is killed)

So failing queries are always slower but some reach nginx but not all? I put stuff in the order I assume they got logged. Not 100% sure this is correct.

To me it looks like some timeout thing that gets triggered a lot.

**Comment by DanielWeigl** [comment]
Its not really a heisenbug i guess, but tor is simply non-deterministic slow.

if i increase the timeout of curl to `-m10` i get all four server respond. Especially if tor has found once a route to a hidden service, its faster afterwards, as long as you dont generate a new tor identity.

We could try to tune the timeouts in our app, that might improve it a bit.

**Comment by dmp1ce** [comment]
I'm happy with a longer timeout. I'm fine with Tor being slow. Maybe a setting to increase the Tor timeout in the app would help.
