### ISSUE TITLE
Local trader suggestion - paid ads

### ISSUE THREAD

**Issue by dmp1ce** [mycelium-com/wallet#215]
I really like the local trader! I think you guys have done a great job with it. However, I have no idea how you are making a money from it. Most of the traders I trade with don't want to conclude the trade with the local trader, so I end up sending to an address of their choosing. I feel bad about that, so it got me thinking about a better payment structure.

Perhaps it would make more sense to charge for the ad, instead of taking a percentage of the trade. This way traders can pay a small fee every so often to renew ads. Maybe charge for ad and percentage of trade.

Really, if it was possible to integrate funcitonality like Backpage.com, into the app, it would be an excellent place to trade locally in private. That would be exciting.

I'm sure this has been thought of before but I thought I'd share just in case.

**Comment by Giszmo** [comment]
I personally agree with the suggested fee change and want to add an argument to it:

* as Mycelium is now earning a %% of the trade, it has to know in some way about the amount, which goes against the desired goal of not knowing about the actual trades. (the end to end encrypted chat goes a long way but is taken ad absurdum by disclosing the amount and the moment the traders met.)
* also, if the listing cost money, scammers would be less motivated to spam to many cities
* A fee would only affect the market makers

**Comment by Rassah** [comment]
Mycelium is still not earning anything off trades. All trades on LocalTrader are free to our users. Our volume is still so small that we wouldn't earn much, and upper management doesn't want to deal with extra possible liability issues if we are any party to the trades (even if we take some of the cut). We also want to keep our volume of traders growing, and imposing fees to put ads would slow that down considerably. So, for now, enjoy the free feature.
