### ISSUE TITLE
Extend URI handling for multiple payments in one transaction 

### ISSUE THREAD

**Issue by weex** [mycelium-com/wallet#216]
I would like to be able to display a QR code for a payment that goes to 3-5 recipient addresses in one transaction but I've discovered the URI scheme only allows for one recipient address. This would be useful for paying for redundant microhosting to hold data for a decentralized labor market.

**Comment by weex** [comment]
An example of the service I would be paying for: https://github.com/ReinProject/causeway/blob/master/spec.md

**Comment by DanielWeigl** [comment]
You can do this via [BIP70](https://github.com/bitcoin/bips/blob/master/bip-0070.mediawiki)

**Comment by DanielWeigl** [comment]
Btw, regarding ReinProject/causeway -> look at https://github.com/bitcoin/bips/blob/master/bip-0120.mediawiki - seems like you want to implement something comparable. Mycelium already supports this.

**Comment by weex** [comment]
Thanks for the pointers. Those BIPs are probably the best way to do this. Call it nostalgia or just liking options but I still like the idea of being able to do this via QR code.

**Comment by Giszmo** [comment]
I guess it's not helpful to go with something other than BIP70 for the QR-codes. BIP70 unfortunately is interactive there but scanning codes with just an address can already be cumbersome, so packing much more data in there is problematic, especially with bad lighting conditions.

I would like to close this issue as "idea, won't fix".

**Comment by Giszmo** [comment]
Extending standards is a difficult process. BIP70 already supports to pay to several addresses with one QR-Code and the suggested alternative would be based on incompatible QR-Codes. We would reconsider this feature in presence of a widely supported BIP though.
