### ISSUE TITLE
URI "decription=

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#218]
I switched to using "message=" since electrum was poorly handling "label=" Now I have to switch back because Mycelium doesn't take "message=" into account. 
https://github.com/spesmilo/electrum/issues/1564

bitcoin:address[?amount=<amount>][?label=<label>][?message=<message>]
https://en.bitcoin.it/wiki/BIP_0021

**Comment by Transisto** [comment]
According to Electrum, and BIP0021 

"The correct way to label a transaction is to use "message""

**Comment by DanielWeigl** [comment]
Good point - we will also check for message, if no label is set. Will be included in the next release.

**Comment by DanielWeigl** [comment]
That is now fixed in the current version - can you try it again?

**Comment by Giszmo** [comment]
assume it's fixed.
