### ISSUE TITLE
HTTP 403 when attempting to pay a BitPay invoice

### ISSUE THREAD

**Issue by leighman** [mycelium-com/wallet#221]
This looks like a BitPay problem but I was able to pay the same invoice using Coinomi so thought it could be a problem in Mycelium handling of the Payment Request (which Coinomi doesn't do)?

When trying to pay the invoice Mycelium cannot broadcast and gives the following error. I have encountered this twice on Black Friday weekend and once today using BitPay through Mycelium but haven't tried another wallet until today.

'Unable to send payment to merchant server. could not send payment to https://bitpay.com/invoice?id=U2PGHNfCyjKjzehDqqmoYz (HTTP 403). The payment will not be broadcasted.'

**Comment by Giszmo** [comment]
Bip70 asks to download a file for further details. We could/should fall back to simple pay to address or at least offer that. On the other hand if the payment server is unreachable, you might not want to sent to this (unreliable) payment processor. We would need more such reports I guess.

**Comment by Giszmo** [comment]
please see #268
