### ISSUE TITLE
testnet android client does not sync up with network

### ISSUE THREAD

**Issue by ser** [mycelium-com/wallet#224]
I sent coins to mquyXb5W2Nq4VaxSHypvrYEoxVFLQ33vtW - there are now more than 74 confirmations https://tbtc.blockr.io/address/info/mquyXb5W2Nq4VaxSHypvrYEoxVFLQ33vtW - but mycelium android wallet still does not see any single satoshi.

**Comment by DanielWeigl** [comment]
restarted Testnet server - is now sync again.

**Comment by tphyahoo** [comment]
I think needs to be started again?

See problems I experienced in #244.

**Comment by Giszmo** [comment]
should work again

**Comment by tphyahoo** [comment]
I think testnet is offline again.

**Comment by Giszmo** [comment]
bitcoind is up to date. wapi was stuck 2h if I read that right. Please try again.

**Comment by tphyahoo** [comment]
broadcasted.

what's wapi?

**Comment by the9ull** [comment]
I think testnet is offline
