### ISSUE TITLE
Clipboard verification also for encrypted keys

### ISSUE THREAD

**Issue by apetersson** [mycelium-com/wallet#23]
Currently it is only possible to verify unencrypted private keys via clipboard.

**Comment by Giszmo** [comment]
#196 is somewhat related.

Anything in the clipboard is somewhat public to all other apps on the phone, so private keys should not go through there. The scanner is part of the app itself, so it's also safe for private keys but encrypted private keys are only somewhat private as [bip38](https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki) allows short, human generated passphrases.
