### ISSUE TITLE
Suggestion: Allow Mycelium to push notification when 1st (or any selected) confirmation is reached.

### ISSUE THREAD

**Issue by alete89** [mycelium-com/wallet#232]
It would be nice if you could set to have a notification when the first, or any desired amount of confirmation is reached. So you can make your transaction, indicate de amount of confirmations "needed" and then stop worrying about that until the notification is pushed.

**Comment by Giszmo** [comment]
Sorry, but we won't implement push notifications for received or confirmed notifications for now. Please see #18 for a prior such request.

**Comment by alete89** [comment]
Understood. Thanks!
