### ISSUE TITLE
National currency calculator not working when wallet is started from URI

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#237]
When I click a URI link and mycelium launch to the transaction page,  the CAD USD value do not show up, ever.

As if the fetching of these thing is done as a prior step in the app.

My solution is to close the wallet, start it, wait for the prices to work then go tap the URI again.

The problem is very consistent.

**Comment by Giszmo** [comment]
Steps to reproduce please.

I just went to [this site](https://www.dokuwiki.org/donate) and clicked the bitcoin address. Mycelium opened the send bitcoins dialog as expected and when I hit `Amount`, I can enter the USD amount and see the BTC amount or any way I want as usual.

**Comment by Giszmo** [comment]
I assume this was a temporary issue
