### ISSUE TITLE
Received amount is counted twice? 

### ISSUE THREAD

**Issue by adamrabbit** [mycelium-com/wallet#246]
I keep a spreadsheet of my bitcoins without really paying attention. Today I noticed that the spreadsheet amount was different from the amount shown in Mycelium.

I hunted everywhere for missing transactions with no luck. Finally I looked for the difference between the spreadsheet and mycelium totals (0.01825049btc) and had one transaction from last November of that exact size. The chance of receiving that exact amount of btc twice seems really unlikely to me.

I'm guessing that one transaction was counted twice. Is there anyway to verify or fix that? Thanks!

**Comment by Giszmo** [comment]
Thank you for reporting this.

Last year, malleability attacks resulted in some confusion for our wallet but we thought to have fixed that with #197 (also see #200).

Could you please go to your account overview, select the account in question and then select "Reload Account" from the context menu? This should fix it for you.

Also please confirm that you are on the latest version v2.6.0

**Comment by adamrabbit** [comment]
Hi, Thanks.

Yes, I have 2.6.0 installed.

I did try to reload the account twice but the total remains the same. I'm not quite sure what I'm doing wrong. This seems to be a little different from #197 in that in the transactions section there are no double transactions. I looked in the Unspent Outputs like in #200 but also there is only one entry for 0.01825049btc.

searching my email for 0.01825049 I only see one purchase from coinbase.

I suppose I can delete the app data and try again... maybe tomorrow.

**Comment by Giszmo** [comment]
You could send all your coins from that account to a new HD account in the same HD wallet and archive the old one. This would also have a positive privacy effect, as currently all addresses of all active accounts are queried with our servers and you might not want to only trust our word that we are not storing how your addresses are connected into one wallet.

As Mycelium does not make it easy to export your transaction history and you might not want to lose your lables, moving funds to a new account would make counting your actual coins easier. If you can send the full amount, your spreadsheeting skills might be the problem. If you can't then we definitely have to investigate how to fix this asap.

**Comment by adamrabbit** [comment]
You're right, the full amount sent. The problem is clearly with my spreadsheet/accounting skills. I had some btc from a few years ago (from mtgox and before) that weren't recorded well until I created the spreadsheet last year. Somehow somewhere I must have purchased 0.01825049 twice I guess.

Anyway, all seems well - Thanks for you help!
