### ISSUE TITLE
Camera upside down on Nexus 5x (probably the Nexus 6 too)

### ISSUE THREAD

**Issue by BillStrait** [mycelium-com/wallet#249]
This has been driving me batty since I got the 5X; the QR code scanner displays the camera upside down. I have been digging for a way to fix this on my end, but it appears to be a quirk with the view. Here's a SO question/answer on the issue: http://stackoverflow.com/questions/35448222/camera-view-is-upside-down-in-my-android-application-for-nexus-5x

**Comment by DanielWeigl** [comment]
https://github.com/mycelium-com/wallet/issues/236 - will get fixed with next update (is currently in beta)
