### ISSUE TITLE
Checking "cold storage" without internet connection

### ISSUE THREAD

**Issue by phplego** [mycelium-com/wallet#25]
Sometimes it is needed to check "cold storage" for what:
* I don't forget BIP38 password
* It is printed correctly

But little bit scared do "import key" with internet connection because of viruses/malware/google backdoors or something else could be on the phone.

In current version when i tap "cold storage" without connection it says after decryption process "error: no connection". So it would be grate to consider about this feature

**Comment by Giszmo** [comment]
There was no progress on this in years. Feel free to re-open if the issue is still a problem.
