### ISSUE TITLE
Chain.com blockexplorer option needs removing

### ISSUE THREAD

**Issue by wizardofozzie** [mycelium-com/wallet#253]
No 40x http error is thrown, so if this defunct service is chosen, transactions appear to be up to date

**Comment by wizardofozzie** [comment]
Although the refresh icon is missing it's hard to notice

**Comment by Giszmo** [comment]
https://explorer.chain.com doesn't have a block explorer anymore. Thanks for reporting.

The block explorer are not used unless you click a link to one of them in the transaction details, so I'm not exactly sure I understand your concern. We'll remove/investigate it anyway.

**Comment by Giszmo** [comment]
I just checked all our available explorers with a random address:

# these look ok

https://blockchain.info/address/152isPjqWe2wxprqggoQw1zECnzFWK9kML
https://btc.blockr.io/address/info/152isPjqWe2wxprqggoQw1zECnzFWK9kML
https://www.smartbit.com.au/address/152isPjqWe2wxprqggoQw1zECnzFWK9kML
https://www.blocktrail.com/BTC/address/152isPjqWe2wxprqggoQw1zECnzFWK9kML
https://insight.bitpay.com/address/152isPjqWe2wxprqggoQw1zECnzFWK9kML
http://blockexplorer.com/address/152isPjqWe2wxprqggoQw1zECnzFWK9kML
https://live.blockcypher.com/btc/address/152isPjqWe2wxprqggoQw1zECnzFWK9kML
https://search.bitaccess.ca/address/152isPjqWe2wxprqggoQw1zECnzFWK9kML
https://www.biteasy.com/blockchain/addresses/152isPjqWe2wxprqggoQw1zECnzFWK9kML
https://www.coinprism.info/address/152isPjqWe2wxprqggoQw1zECnzFWK9kML
https://tradeblock.com/blockchain/address/152isPjqWe2wxprqggoQw1zECnzFWK9kML
https://www.blockonomics.co/#/search?q=152isPjqWe2wxprqggoQw1zECnzFWK9kML

# this claims to have a temporary issue (cloudflare). localbitoins still links it.

https://chain.localbitcoins.com/address/152isPjqWe2wxprqggoQw1zECnzFWK9kML

# these look dead

http://explorer.chain.com/addresses/152isPjqWe2wxprqggoQw1zECnzFWK9kML
http://blockchains.io/btc/address/152isPjqWe2wxprqggoQw1zECnzFWK9kML

**Comment by wizardofozzie** [comment]
I was using testnet. I'd send coins from a faucet, but the balance would never show up. This was obviously because the service was defunct, which i only just realised

**Comment by jonathancross** [comment]
Perhaps there some way these links could be checked as a unit test?

**Comment by Giszmo** [comment]
Good point. This would be something for zabbix though. But ... this has currently kind of low priority as we are working on a replacement. Closing as it's been fixed for now.
