### ISSUE TITLE
Show unspent output private key

### ISSUE THREAD

**Issue by raedah** [mycelium-com/wallet#254]
Please have an option to show the private key (qr code) on the 'show unspent outputs' view.

**Comment by Giszmo** [comment]
Could you share a use case for that, please. Mycelium is a power-user wallet but at some points we would still opt for security over flexibility. Here for example it's not well known to users that sharing an account level xpub key and an address's priv key would leak their xpriv key rather trivially.

To quote [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki):

> One weakness that may not be immediately obvious, is that knowledge of a parent extended public key plus any non-hardened private key descending from it is equivalent to knowing the parent extended private key (and thus every private and public key descending from it). This means that extended public keys must be treated more carefully than regular public keys. It is also the reason for the existence of hardened keys, and why they are used for the account level in the tree. This way, a leak of account-specific (or below) private key never risks compromising the master or other accounts.

**Comment by raedah** [comment]
Use case is wanting to move funds between my own wallets without needing to create a new on-chain transaction that will cost another fee. I tried using https://coinb.in/ to find the priv key with the xpub and xpriv, but was not able to get it to work. Sounds like the issue you mentioned is averted if the key is "hardned".

**Comment by Giszmo** [comment]
The concept of hardened key is confusing, too. The intuition says that if the account level key is hardened, it's "hardened against attacks or something" but unfortunately it goes the other way around. A hardened account level key does not leak information about the master key for example.

Having only an xpub key, you can't derive to hardened keys below that.

**Comment by DanielWeigl** [comment]
Closing due to high chance of users making a fatal mistake.

You can for example try to use http://webhdwallet.github.io/ if  you want to export a private key

**Comment by raedah** [comment]
Not sure why its dangerous to show the user an individual private key, but its great to show the user the master private key. Ooook.

**Comment by DanielWeigl** [comment]
> Not sure why its dangerous to show the user an individual private key
exactly therefor its so dangerous - did you read the quote leo posted above? If you give someone the full xpriv, you expect he will have access to all funds in it.

If you give someone the xpub you expect him to know all your funds, but not be able to spend it

If you give someone the private key of one key from an HD-account you expect he will be able to spend the funds of this particular key and not more.

Problem is, if you give someone the xPub and one private key of it, the whole concept fails and he will be able to generate the xPriv of this account, and thus spend all funds.

**Comment by raedah** [comment]
Okay, thanks for the clarification.

**Comment by raedah** [comment]
Still the possibility of using a hardened key, as discussed above. "a leak of account-specific (or below) private key never risks compromising the master or other accounts". But I understand if its not a priority.

**Comment by DanielWeigl** [comment]
No, thats not possible - it wouldnt be compatible with Bip44 (and other wallets) and it would make xPub-keys unusable. (because, if its hardened you can not derive public keys from it)
