### ISSUE TITLE
show fee by default

### ISSUE THREAD

**Issue by raedah** [mycelium-com/wallet#256]
Going to the Send view, says at the top Enter Recipient Address, and then down below is the Miner Fee with a button that says 'Priority'. 

This view only shows the miner fee after an amount is entered. I find it preferable that it would show the fee by default and then modify it if needed when the amount changes. Seeing the fee is useful here, and if there is no money in the wallet, then there is no way for the user to see the fee at all.

**Comment by Giszmo** [comment]
The fee is calculated based on the actual transaction. While most people have about 250B per transaction, everybody will have 330B or more at some point and this depends on the amount you are trying to spend. This is the reason why the fee is only shown after the amount is entered.

That said, I agree that it would be desirable to see the fee, maybe assuming a send-all transaction which is maybe even cheaper than a different amount.

**Comment by raedah** [comment]
bitcoin-qt shows estimate fees before a tx is created, so it seems reasonable. It just modifies the estimate (if needed) once it has more information about the tx.

**Comment by DanielWeigl** [comment]
The shown fee will not be usable for the average user. Either we show it as "mBtc/1000bytes" or "sat/byte" - it then depends how big the tx is and that can range from 200bytes to >1000bytes, if you need many inputs. so it may be off by factor 5 and more.

**Comment by raedah** [comment]
@DanielWeigl I disagree. Bitcoin Core shows a default transaction fee before it knows anything about the transaction inputs, and its quite useful. I don't see any information about how you determined a 'factor of 5'. Is that based on data?
