### ISSUE TITLE
v2.7.1 warns about RBF for non-RBF transactions

### ISSUE THREAD

**Issue by dooglus** [mycelium-com/wallet#257]
I just sent a transaction from Bitcoin Core v0.12 to Mycelium v2.7.1. Before the transaction confirmed there was a red warning in the Mycelium transactions list:

  "WARNING: wait for at least one confirmation! (RBF)"

but the transaction isn't an RBF transaction.

According to [BIP 125](https://github.com/bitcoin/bips/blob/master/bip-0125.mediawiki#Summary) a transaction is RBF if "any of its inputs have an nSequence number less than (0xffffffff - 1)". My transaction has a single input, and its nSequence number is equal to (0xffffffff - 1), not less than it. It has no unconfirmed inputs.

Here's a dump of the transaction from Bitcoin Core:

    $ bitcoin-cli getrawtransaction 4a0252c35d2d92a428a836313b8b7d7a05c07d5107fbfe1df2bee65944961488 1
    {
      "hex": "010000000190f55e38240ab795f7e11df5e272d699b525c0e50af69733fda1b583c4273c23000000008a47304402206a945b64ae1478f1ed1374d3f1bd0b9db66b424804efb3ce59b38293a25f5caf022037695fe1b04a07569e0f6c019aa406492294151f3a0e88cae2c53ed713d5c6d50141048fd4539156a8ad9ef7e885cead013bf5377de67e05aa34b662c6431f684c1d61d83b690fb8feeeb69c305b4043f8d3dbb4f2847feaf767e8eac1e51e9c4425b2feffffff025e31920b000000001976a914152e9f6874a0768ada32f1c8c5fc80337fd7ee5988ac00e1f505000000001976a914d3f9702528b302dbadcbbe26e91001c2e453814088acb4270600",
      "txid": "4a0252c35d2d92a428a836313b8b7d7a05c07d5107fbfe1df2bee65944961488",
      "size": 257,
      "version": 1,
      "locktime": 403380,
      "vin": [
        {
          "txid": "233c27c483b5a1fd3397f60ae5c025b599d672e2f51de1f795b70a24385ef590",
          "vout": 0,
          "scriptSig": {
            "asm": "304402206a945b64ae1478f1ed1374d3f1bd0b9db66b424804efb3ce59b38293a25f5caf022037695fe1b04a07569e0f6c019aa406492294151f3a0e88cae2c53ed713d5c6d5[ALL] 048fd4539156a8ad9ef7e885cead013bf5377de67e05aa34b662c6431f684c1d61d83b690fb8feeeb69c305b4043f8d3dbb4f2847feaf767e8eac1e51e9c4425b2",
            "hex": "47304402206a945b64ae1478f1ed1374d3f1bd0b9db66b424804efb3ce59b38293a25f5caf022037695fe1b04a07569e0f6c019aa406492294151f3a0e88cae2c53ed713d5c6d50141048fd4539156a8ad9ef7e885cead013bf5377de67e05aa34b662c6431f684c1d61d83b690fb8feeeb69c305b4043f8d3dbb4f2847feaf767e8eac1e51e9c4425b2"
          },
          "sequence": 4294967294
        }
      ],
      "vout": [
        {
          "value": 1.94130270,
          "n": 0,
          "scriptPubKey": {
            "asm": "OP_DUP OP_HASH160 152e9f6874a0768ada32f1c8c5fc80337fd7ee59 OP_EQUALVERIFY OP_CHECKSIG",
            "hex": "76a914152e9f6874a0768ada32f1c8c5fc80337fd7ee5988ac",
            "reqSigs": 1,
            "type": "pubkeyhash",
            "addresses": [
              "12w13Rv4FzxbSbAvbRLTppmSjRUXrDFw6S"
            ]
          }
        }, 
        {
          "value": 1.00000000,
          "n": 1,
          "scriptPubKey": {
            "asm": "OP_DUP OP_HASH160 d3f9702528b302dbadcbbe26e91001c2e4538140 OP_EQUALVERIFY OP_CHECKSIG",
            "hex": "76a914d3f9702528b302dbadcbbe26e91001c2e453814088ac",
            "reqSigs": 1,
            "type": "pubkeyhash",
            "addresses": [
              "1LKpPjk72AXRzEZCCfDFoJfnvX9UNmSHdF"
            ]
          }
        }
      ]
    }

**Comment by DanielWeigl** [comment]
Hi dooglus, thx for reporting - i also checked the funding tx (233c27c483b5a1fd3397f60ae5c025b599d672e2f51de1f795b70a24385ef590) which was only mined 6 blocks ahead. But this isnt also not RBF (if any unconfirmed parent of an transaction is marked for RBF youll get this warning).

Are you sure you got this warning and not "WARNING: wait for at least one confirmation! (Unconfirmed parent)"?

If you somehow can reproduce it, please report back.

**Comment by DanielWeigl** [comment]
Hi again, 

just checked our backend and there really was a bug with Sequence=MAX_INT-1 - is now fixed and will deployed later on... thx again for reporting

**Comment by dooglus** [comment]
Looks like I'm too late and you fixed it already, but the parent was already confirmed when I spent it, and I'm sure it said what I claim it said. I have a screenshot, but doubt it's necessary now.
