### ISSUE TITLE
Barcode scanner problem

### ISSUE THREAD

**Issue by plachta11b** [mycelium-com/wallet#260]
Barcode scanner does not work after update. I use android 4.4.4 custom rom on LG P760. Factory reset does not help. Screen with error have bad rotation. All other applications works fine.

**Comment by DanielWeigl** [comment]
Can you send us a more detailed error description or a screenshot of it?

Does the app crash? 

Am 3. April 2016 18:32:53 MESZ, schrieb Jan Holcak <notifications@github.com>:
>Barcode scanner does not work after update. I use android 4.4.4 custom
>rom on LG P760. Factory reset does not help. Screen with error have bad
>rotation. All other applications works fine.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mycelium-com/wallet/issues/260

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by plachta11b** [comment]
No crash only error message. I can not take screenshot (can not write to SD card error) in mycelium barcode scanner.

![20160404_134432_hdr](https://cloud.githubusercontent.com/assets/6261620/14247062/c3776260-fa6b-11e5-86cd-86168abd6647.jpg)

**Comment by DanielWeigl** [comment]
Hi, so far i was not able to reproduce the error or pin it down any further. 

> (can not write to SD card error)
Can you try to fix that problem? Unlikely, but maybe its also the root cause for this problem?

**Comment by plachta11b** [comment]
I have some news. My phone does not start and i use warranty service. They change camera module so that can be hardware issue. It is strange because all other applications works perfect. Sorry, this is probably false issue.
> Can you try to fix that problem?

Screenshot works outside of mycelium so I have no idea how to fix it.

**Comment by Giszmo** [comment]
thanks for reporting back.

**Comment by mpd518** [comment]
This seems to have not yet been fixed in the latest Android release of mycelium. I can repro this issue on my Android phone 100% of the time.
