### ISSUE TITLE
can't accept trades

### ISSUE THREAD

**Issue by kilorat** [mycelium-com/wallet#261]
I use localtrader almost every day. Everything worked on April 5th, but after the 7th, the accept trade button stopped working. I put in an ad for selling BTC, and the other person responds to it. The accept trade button is not greyed out, and it animates when I push it, but it doesn't do anything. I can chat with the other person, cancel the trade, and update price. Everything works but the accept trade button.
I'm using a LG Nexus 5x
mycelium 2.7.3 (whatever newest on google play is)
I tried rebooting my phone, and I had the other person open a new trade, we tried that several times but the problem persists.

update: I put a sell ad, and the exact problem occurred for the other person, so it's not just my phone.

**Comment by thorie7912** [comment]
Seeing the same problem on my Moto X running 4.2.2

**Comment by kilorat** [comment]
I see the most recent commit says this is fixed
https://github.com/mycelium-com/wallet/commit/2e138e855f06be6c881729a611ce135d9737aaff
I guess we just have to wait for the next release now.

**Comment by DanielWeigl** [comment]
Yes, should hit the playstore within the next hour
