### ISSUE TITLE
scanning this payment QR code crashes mycelium

### ISSUE THREAD

**Issue by thorie7912** [mycelium-com/wallet#262]
![crashes-mycelium](https://cloud.githubusercontent.com/assets/869094/14407999/d9ed6cc8-fe95-11e5-878d-1ca6f0771dcb.png)

I was trying to send payment to this QR code and it crashed mycelium.
At first it says "Fetching payment address"
And then it crashes on my Android phone with "Unfortunately, Mycelium Wallet has stopped"

I have a 1st gen Moto X running 4.2.2

**Comment by DanielWeigl** [comment]
The associated paymentrequest from https://www.coinify.com/  ( https://www.coinify.com/pr/W0/4h3c ) has "null" as amount set for the output (i.e. the amount to be paid is not specified).

This is valid according to bip47, but we handle it currently in a wrong way. Fix will be included in the next update.

**Comment by DanielWeigl** [comment]
Was fixed long ago but i missed to close this issue.
