### ISSUE TITLE
Backup error message: "You have to wait for ... ~ 8 years"

### ISSUE THREAD

**Issue by fortran77** [mycelium-com/wallet#263]
Actual bitcoin private keys are included below. I am not going to use them in real life, and neither should anybody else.

Android 6.0.1, Mycelium 2.7.3.

While experimenting with importing keys across wallets, I went to https://bip32jp.github.io/english/ and it generated this random BIP39 passphrase:

    magic goat camp daring mutual unfair captain biology coin biology lens evil

and this derived private key:

    xprv9yQDidb3yx5eJWzoAgu2pNBrK1AFkSzsdrNhLjvDpQNtrg6t2ehWD769bWu2GVDYCsiypp9pSfiZywuz3VYFojkjH8yQrC1FUi4q3nkAtuP

I supplied no password in the Optional password field.

Out of curiosity, I imported the above derived private key into Mycelium by first pasting it into the Android clipboard, and then going to: Accounts => Add Account => Advanced => Enter PIN code => Clipboard => Edit Account label => OK.

This gave me a new account containing one private key.

Then with the new account selected, I did:  (three vertical dots) => Backup => Enter PIN Code.

The screen I reached then gave me the subject error, which is where I think something went wrong. The error messages said: "Sorry, an additional backup is currently not possible. Your PIN was recently changed" and "You have to wait for at least 405507 blocks (~ 8 years)."

The error is reproducible if I delete the new account and add it back all over again using exactly the same derived private key shown above.

There are two possible issues here.

First, I have not recently (during the last few days) changed the PIN. However, I don't know how recently is considered "recently".

Second, and more importantly, 8 years is a long time to wait to do a backup.

![android-6 0 1-mycelium-2 7 3-screenshot](https://cloud.githubusercontent.com/assets/6755457/14596353/be931caa-04fa-11e6-9629-fe5653f3bfa7.png)

**Comment by DanielWeigl** [comment]
Hello, yes the 8y are clearly a bug, ill look into it. 

The other point we need to probably make more clear: if you make a backup, it is only valid for the main HD-Accounts, but _not_ for other imported accounts. (As you have imported them, we assume they also exist somewhere else)

**Comment by Giszmo** [comment]
fixed by DanielW in af52116c
