### ISSUE TITLE
BIP 73 support?

### ISSUE THREAD

**Issue by bitjson** [mycelium-com/wallet#264]
Hi there, what is the status of [BIP 73](https://github.com/bitcoin/bips/blob/master/bip-0073.mediawiki) support in Mycelium? It would be great if the wallet was able to handle the lower-density codes!

**Comment by DanielWeigl** [comment]
Hello - it is supported since about 1y. did you experience it otherwise with some paymentrequest/QR code?

**Comment by bitjson** [comment]
Great! thanks for the info. I think the issue may have been from an old version of Mycelium.
