### ISSUE TITLE
How many unused addresses Mycelium check in an xPub ?

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#266]
Lets say I send bitcoin to a derived address 50 N further than the last used address, at which N+ value will the amount stop showing up in the wallet ?

**Comment by Giszmo** [comment]
Mycelium is scanning according to BIP44, so gaps bigger than 20 will not be scanned on the external chain. On the internal chain there is some recent change that also extends the look-ahead to 20 to deal with other wallets that caused big gaps.
