### ISSUE TITLE
Implement estimate fee for miner fees instead of hardcoding

### ISSUE THREAD

**Issue by chris-belcher** [mycelium-com/wallet#267]
Mycelium uses hard coded values for the fee/kb miner fee.

https://github.com/mycelium-com/wallet/blob/4cdbb185b123875c6fb990af161bbc1bb7d784ac/public/wapi/src/main/java/com/mycelium/wapi/api/lib/FeeEstimation.java#L14-L22

In a time of rising fees, these values can lead to a bad user experience of transactions taking a long time to confirm.

Since Mycelium queries a server for it's blockchain data, probably the best way to implement this is to have the server use the `estimatefee` RPC call on bitcoind and send it to the wallet.

**Comment by Giszmo** [comment]
Hi Chris,

check out https://github.com/mycelium-com/wallet/blob/4cdbb185b123875c6fb990af161bbc1bb7d784ac/public/wapi/src/main/java/com/mycelium/wapi/api/Wapi.java#L148

The code you found is just the fallback. It might be worth reviewing these values if they serve well as a fallback but it should almost never fallback on these anyway.

**Comment by chris-belcher** [comment]
Thanks Leo! I should never have doubted Mycelium.

I got the idea for this issue because of a few cases of long confirmation times today

https://www.reddit.com/r/BitcoinMarkets/comments/4k6hnt/daily_discussion_friday_may_20_2016/d3cuk1j?context=1

https://www.reddit.com/r/BitcoinMarkets/comments/4k6hnt/daily_discussion_friday_may_20_2016/d3ctb9j

So I wonder what happened. Maybe the required fee rose very quickly so the estimatefee algorithm got it wrong?

**Comment by Giszmo** [comment]
Quote from [your first link](https://www.reddit.com/r/BitcoinMarkets/comments/4k6hnt/daily_discussion_friday_may_20_2016/d3cuk1j?context=1)

> I send the transaction using Mycelium and I use "Average" fees, which come out to 24 satoshi per byte

Doesn't sound like any of the standard values.

In the second link you talk a bit like the targets for confirmation times were in any way predictable. As miners don't prioritize old transactions (they are modeled to be greedy profit maximizers), 20sat/B that didn't make it into a block, floats around like a new transaction broadcast after the block was mined. If the cut-off rate was 21sat/B in that block, it wouldn't have made it in if it had been around for a week. It's just that thanks to volatility in the gaps between blocks, there are events in which three blocks are found in 10 minutes and assuming the transaction volume is more regular overall, those events can substantially lower the cut-off rate, giving cheaper transactions a chance to make it in.

In that sense, the target confirmation times are very much subject to high variance and that's also why we don't advertise them as confirm in 10 minutes, 30 minutes, 2 hours but as high priority etc.

**Comment by Giszmo** [comment]
Also as a fallback, default fees should probably be dynamic somehow. Median of last ten RPC values times two or so. Else we will not be prepared for any fee events.
