### ISSUE TITLE
testnet transaction troubles

### ISSUE THREAD

**Issue by jlopp** [mycelium-com/wallet#270]
Hi Mycelium folks,

I was wondering if you're having any issues with your testnet servers. I tried to send several transactions last night but they don't appear to be hitting the network.

If your testnet servers are operational, can you provide me with any way to retrieve the raw transaction hex so that I can inspect it myself? I can only figure out how to get the hash, which isn't helpful since the testnet block explorers don't have the transaction.

**Comment by DanielWeigl** [comment]
Hi, thanks for the hint. Yes our testnode got stuck on a wrong branch. ive just restarted it and it needs some time to catch up

**Comment by jlopp** [comment]
Should sending be fixed now? I'm still unsuccessful in broadcasting a transaction from my testnet wallet. My wallet is also showing two other sends that are clearly invalid because they're trying to spend from spent outputs; not sure if that would stop the valid transaction from being broadcast. Let me know if you need more info.

**Comment by Giszmo** [comment]
Can you refresh your accounts? Accounts tab -> options -> refresh.

Hope that helps but it should happen once every 24h anyway.

**Comment by jlopp** [comment]
Yeah, I've tried refreshing multiple times. Any way I can get more debug
info for you?

**Comment by Giszmo** [comment]
We have to look into it and will let you know if there is any additional info you could provide. If you see anything suspicious in settings ->

**Comment by DanielWeigl** [comment]
Can you try to cancel the outgoing failed transactions? they might be based on already spent UTXOs and will never confim. Also they will have created new UTXO (change output) which the wallet now tries to spent again, which are counted as invalid by the network.

Select the transaction and in the menu "delete" and reload account afterwards

**Comment by jlopp** [comment]
Wanted to check in on this again: I haven't been able to successfully broadcast a testnet transaction since opening this case.

I currently have one stuck send in my wallet that is trying to spend the second output from this transaction: https://www.blocktrail.com/tBTC/tx/29185b1e4421df4d79d9497c9d1ad2868c1d709c5bdb60bad8e9abc4ddec361f

However, I have a really hard time actually cancelling sends in my wallet. Very rarely does the wallet give me an option to delete the send, even after it has been trying to send for several days.

**Comment by DanielWeigl** [comment]
the "delete" option is only available if the transaction was never successfully send to our serves (e.g. for transaction you tried to broadcast while being offline, but you settled them otherwise in the meantime).

On testnet wich often forks that logic might fail (tx got broadcasted on a fork, blockchain reconfigured and tx is now invalid but marked as sent).

Can you restore from the masterseed and see if that helps?

**Comment by jlopp** [comment]
I uninstalled the testnet wallet (is there not a way to clear the master seed?) reinstall, and restored from the master seed. It's showing my expected balance but the stuck unbroadcasted send still shows up. In case it helps, the tx hash is: 9c4d536663a420773ae22cce55013bd7bd8b94ce92113c22c770bec3d4d62bc5

**Comment by Giszmo** [comment]
Looks like testnet needs a restart. This tx hash is unknown to testnet according to [insight](https://test-insight.bitpay.com/tx/9c4d536663a420773ae22cce55013bd7bd8b94ce92113c22c770bec3d4d62bc5).

**Comment by jlopp** [comment]
Still not having any success. I deleted the stuck send and created a new
one, but it doesn't appear to be broadcasting:
http://tbtc.blockr.io/tx/info/3190f85f890d064784ff6b59c5360906c3def064181b885c688b93a1572a581f

**Comment by DanielWeigl** [comment]
Hi,

can you share the testnet xPub for this account or the whole masterseed with us. Either here or send it to developers@mycelium.com

Thank you

**Comment by jlopp** [comment]
tpubDCV6cMNdgnb2vEkjq9BNsqqxHneBgbZU9H6deszP6QxMvpt6emMCCfsSkQDRxiVY7WMKcXcJcJWw5D9qReGMJovXRe826beR3qoDtY4Evxr

The latest stuck send is spending a single input from mqwm8qXpU7aMR3jiHPN36Zjusa7LJzvCBV

**Comment by jlopp** [comment]
Any ideas? Is there any way for me to extract the raw transaction hex for a send so that I can inspect it myself?

**Comment by Giszmo** [comment]
For easy importing:
![download](https://cloud.githubusercontent.com/assets/96378/16526475/cbe83ddc-3f87-11e6-845c-a0f2cecde212.png)

Testnet is slow. It got "31 addresses" and I still see no transaction history and now it's "32 addresses" … 52 … so slow. Will check the servers.

**Comment by Giszmo** [comment]
I'm confused.

```
# /testnet/bitcoind/info.sh 
{
  "version": 120100,
  "protocolversion": 70012,
  "walletversion": 60000,
  "balance": 4450.40968574,
  "blocks": 891910,
  "timeoffset": 0,
  "connections": 9,
  "proxy": "",
  "difficulty": 169943.6842417648,
  "testnet": true,
  "keypoololdest": 1384789398,
  "keypoolsize": 107,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": "Warning: unknown new rules activated (versionbit 28)"
}
```

Again, `"blocks": 891910` is consistent with what [bitpay](https://test-insight.bitpay.com/) says.

I'm not sure what `"errors": "Warning: unknown new rules activated (versionbit 28)"` is about or if it might have to do with the issue.

The transaction 3190f85f890d064784ff6b59c5360906c3def064181b885c688b93a1572a581f is unknown to bitpay and re-broadcasting doesn't change that.

Hitting re-broadcast reaches the server and the server claims to have successfully re-broadcast the transaction. I'm not quire sure where it's stuck or where the client has the transaction from in the first place. I suppose its our BQS database but that's where I would like to hand back to @DanielWeigl

**Comment by Giszmo** [comment]
Maybe that helps:

```
$ curl -m4 -s -k -X POST -H "Content-Type: application/json" -d '{"version":1,"txIds":["'3190f85f890d064784ff6b59c5360906c3def064181b885c688b93a1572a581f'"]}' https://node3.mycelium.com/wapitestnet/wapi/getTransactions | json_pp 
{
   "errorCode" : 0,
   "r" : {
      "transactions" : [
         {
            "txid" : "3190f85f890d064784ff6b59c5360906c3def064181b885c688b93a1572a581f",
            "time" : 1467233753,
            "unconf_chain" : 0,
            "binary" : "AQAAAAGBHtxOnDOXlRP9RrzWbunjlSUZAgLbapOvcOySPBYNowAAAABrSDBFAiEAxHVAwj2Cvo6VlmmaaF/WBP9JZVKdUto4PWRMyBAZD+YCIH/DOZ1aCGQvkRFvu4Lm8FcveU6Svx4yelNnbB8Sz+QUASECzbnvskbQ4xW5dWJaJvPO+U8e0B6qql7RGu8SvSKcSar/////AgBlzR0AAAAAF6kU70iQjqmciTAiPobDd1oFcX4N4EaHyVN4WsUFAAAZdqkURo5QVSRIp6sUft13AFUQjkddnzWIrAAAAAA=",
            "height" : -1,
            "rbf" : false
         }
      ]
   }
}
```

**Comment by jlopp** [comment]
Decoded; it looks alright at first glance. I could try pushing it to nodes manually though I'll hold off.

<pre>
{
  "txid": "3190f85f890d064784ff6b59c5360906c3def064181b885c688b93a1572a581f",
  "size": 224,
  "version": 1,
  "locktime": 0,
  "vin": [
    {
      "txid": "a30d163c92ec70af936adb0202192595e3e96ed6bc46fd139597339c4edc1e81",
      "vout": 0,
      "scriptSig": {
        "asm": "3045022100c47540c23d82be8e9596699a685fd604ff4965529d52da383d644cc810190fe602207fc3399d5a08642f91116fbb82e6f0572f794e92bf1e327a53676c1f12cfe414[ALL] 02cdb9efb246d0e315b975625a26f3cef94f1ed01eaaaa5ed11aef12bd229c49aa",
        "hex": "483045022100c47540c23d82be8e9596699a685fd604ff4965529d52da383d644cc810190fe602207fc3399d5a08642f91116fbb82e6f0572f794e92bf1e327a53676c1f12cfe414012102cdb9efb246d0e315b975625a26f3cef94f1ed01eaaaa5ed11aef12bd229c49aa"
      },
      "sequence": 4294967295
    }
  ],
  "vout": [
    {
      "value": 5,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_HASH160 ef48908ea99c8930223e86c3775a05717e0de046 OP_EQUAL",
        "hex": "a914ef48908ea99c8930223e86c3775a05717e0de04687",
        "reqSigs": 1,
        "type": "scripthash",
        "addresses": [
          "2NF4SR1jsXz33xSmBmFWxy9GEree3W5H6Wh"
        ]
      }
    },
    {
      "value": 63451.84531401,
      "n": 1,
      "scriptPubKey": {
        "asm": "OP_DUP OP_HASH160 468e50552448a7ab147edd770055108e475d9f35 OP_EQUALVERIFY OP_CHECKSIG",
        "hex": "76a914468e50552448a7ab147edd770055108e475d9f3588ac",
        "reqSigs": 1,
        "type": "pubkeyhash",
        "addresses": [
          "mmx25cp6uqSN9MvQ8LX6rmce5Gw9oMzTBT"
        ]
      }
    }
  ]
}
</pre>

**Comment by Giszmo** [comment]
Thank you for holding off but I don't know when @DanielWeigl might be available to look into this. I'm not enough involved in our backend to dig into this efficiently on my own.

**Comment by Giszmo** [comment]
@jlopp hold your horses. Our server is syncing and it should work to re-broadcast from within the app in some minutes.

**Comment by DanielWeigl** [comment]
Okay, i think i found the culprit... it was me after all... i migrated the testnet node to a new server two weeks ago and it has a special mode to faster catchup with the blockchain, where it does not connect to outside nodes.
Thats the reason your broadcast silently failed. Sorry it took me so long to realize. It should work now. I havent broadcasted it manually - curious if it works from within your app.

**Comment by Giszmo** [comment]
The tx is broadcast now. I switched to the Mycelium testnet app and instantly got the insight beepbeepbeepbeep.

**Comment by jlopp** [comment]
Confirmed; thanks. Testnet can be a pain sometimes.
