### ISSUE TITLE
trying to enter an amount to send crashes the app

### ISSUE THREAD

**Issue by thorie7912** [mycelium-com/wallet#272]
steps:
1. tap send
2. tap Scan QR Code
3. scan a QR code
4. tap the Keyboard Icon
5. watch the app crash into oblivion..... :(

this is horrible, all my bitcoins are stuck within the app and i can't release them

please fix this!! the whole point of a wallet is to send and receive funds!!

android 4.2.2
mycelium 2.8.0

same crash when i scan a QR code that has an amount associated with it

**Comment by Giszmo** [comment]
This sounds an awful lot like a bug we so far only got via crash reports. We were wondering why nobody who struggled with this, would get in touch with us, so I hope you can help us to reproduce it here, as it's really hard to figure out.

Please do send your crash report (or nod if you have a Sony Xperia Z1 C6903 and sent a crash report 20 minutes ago.)

If you need to spend your coins quickly then you can do so with any BIP39/BIP44 compatible wallet and your backup passphrase.

If you could produce a log from around the crash, that could maybe help us figure out what's happening. Else, I started digging into the relevant code yesterday and guess I fixed another bug, so maybe discussing that one helps us find the cause.

If sharing your xpub key with us would be an option, then please send it to developers@mycelium.com, referring to this issue #272.

The crash reports we get are of the form:

    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mycelium.wallet/com.mycelium.wallet.activity.GetAmountActivity}: java.lang.RuntimeException: Unable to find public key for address [address hidden] acc:class com.mycelium.wapi.wallet.bip44.Bip44Account
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)

**Comment by thorie7912** [comment]
I just sent a crash report, from Moto X. Let me know what else I can do to help fix this issue.

**Comment by Giszmo** [comment]
Please figure out where in the HD tree the address `1J6…` is located, or share your `xpub` with us.

**Comment by thorie7912** [comment]
I just sent the `xpub` key to the email you gave.

**Comment by Giszmo** [comment]
The email conversation was interesting in that the bitcoin address from the crash report was not derived from the provided `xpub`. It would be interesting to find where Mycelium pulled that address. If it's from a different account, in which case it would be a severe bug in Mycelium but it would not explain why the public key would be missing. Or was it the recipient's address, in which case it would be natural that no pub key was available but why would it expect to have it? OP, please find this address `1J6...`. It's actually a used address with UTXOs (spendable funds). All addresses from similar crash reports have UTXOs. Some have several UTXOs but some just one. I only checked the last 5 addresses.

**Comment by thorie7912** [comment]
I was able to fix this by going to the Accounts tab, selecting my HD account, clicking the Menu, and selecting Reload Account. 

After that, I could enter an amount again without the app crashing.

Thanks for all the help

**Comment by Giszmo** [comment]
Thanks to A.Z.'s observations, Constantin could reproduce this. It seams to have to do with checking the balance of some address in the address book resulting in that external address getting added to the current account. We will release a fix soon. Most likely on Monday.

**Comment by DanielWeigl** [comment]
Hi, a fix to prevent this issue in the future just got deployed.

**Comment by DanielWeigl** [comment]
That got fixed in the last release. It might be necessary to reload the account once, if it still crashes.
