### ISSUE TITLE
Security - Mycelium should timeout 

### ISSUE THREAD

**Issue by getkaizer** [mycelium-com/wallet#274]
Hello,
I use Mycelium on android. I find that if i press the "home" button on the android handset, i am able to navigagte to the home screen of my device. However, if i press the "processes" button, I can flip through the various programs that are in the background and Mycelium is also visible. But what is troubling is that i can tap Mycelium and get back to my wallet without any hindrance or "gating" mechanism from Mycelium.
This poses as security threat and ideally, the user should be re-asked to enter the correct password at every attempt of accessing the Mycelium wallet from "outside" Mycelium.

I'd appreciate if you could treat this as a priority.

EDIT: Ideally, i should be able to set a timeout between 5 minutes and 15 minutes. So, after, for example, 5 minutes of inactivity, Mycelium should automatically time out.

Thanks and Regards,
Getkaizer.

**Comment by Giszmo** [comment]
Leaving the app with the `back` button actually closes it and then you would have to enter your pin (if you have configured it) the next time you use it.

The `processes` button actually shows a list of recent processes, not of running processes. For Android they took a huge effort of making apps act as if they were running in the background even the app had to be stopped, so you can receive a call, switch away from your app, do the call, open other apps during the call and get back to where you left off before.

For the way Android works, I feel it's actually hard to implement a timeout that refreshes on activity and a hard timeout would be really annoying. Should the timeout be refreshed while you are in local trader? How about while you are in your browser, reading our webpage, started from the app? How about the QR-Code scanner (we provide the scanner but other wallets don't and doing timeout stuff there is weird. What if you get a call while scanning?)?

But given most users have no clue about `back` actually closing the app, maybe a logout button on the main screen (only visible if a pin is required at login) would resolve your issue?

**Comment by jonathancross** [comment]
> a logout button on the main screen

I like this idea.
Might consider calling this something like "Lock wallet" as the user didn't necessarily "login" to any service.

**Comment by Giszmo** [comment]
Should be easy to implement. Pull requests welcome.

**Comment by getkaizer** [comment]
Thanks Mycelium!
I now see a lock option on the accounts section of my wallet! I appreciate your efforts!

**Comment by getkaizer** [comment]
Closing issue as it satisfied my request. Thanks Mycelium!
