### ISSUE TITLE
The fee is not calculated on the basis of the actual situation

### ISSUE THREAD

**Issue by Perlover** [mycelium-com/wallet#276]
Hi,

I noticed that normal comission is every time is 22-23 satoshi/byte. In any time even when there is 30MB pool size! :( Today i made transaction with normal comission and i am waiting already 6 (six) hours! Because there 30k transactions and 30MB pool of transaction in bitcoin network. And Mycelium's normal fee even now is 23 satoshi/byte

Can you make something with this? Is your fee hardcoded? Or fee is fed by your servers and there not actual info?

**Comment by Giszmo** [comment]
Our server reports 46sat/B for the "normal" fee, which is a three block target:

```
$ curl -m4 -s -k -X POST -H "Content-Type: application/json" https://mws2.mycelium.com/wapi/wapi/getMinerFeeEstimations | json_pp 
{
   "r" : {
      "feeEstimation" : {
         "validFor" : 1466096340324,
         "feeForNBlocks" : {
            "2" : "56115",
            "5" : "37984",
            "10" : "35220",
            "4" : "37984",
            "1" : "120000",
            "15" : "28282",
            "3" : "46138",
            "20" : "28282"
         }
      }
   },
   "errorCode" : 0
}
```

But I can confirm I also get 23sat/B. I'm investigating.

**Comment by Transisto** [comment]
I've checked my last 50 transactions and all of them are 23sat/B or below.
How can this be possible !!!

**Comment by Giszmo** [comment]
Ok, it seams it's actually using a default fee but not quite neither, as that would be 20sat/B. It's 23sat due to the fee getting estimated generously I guess.

It never asks the server because of [this](https://github.com/mycelium-com/wallet/blob/master/public/wapi/src/main/java/com/mycelium/wapi/wallet/WalletManager.java#L763) always being false. I assume we will publish a fix today.

**Comment by Transisto** [comment]
Not to stress you up more, but if the default/normal fee is 20-23sat and for the last month there was only a few hours that would have made a 23sat transaction lucky to fit in 6th+ blocks. This should have been an emergency situation a while ago !
