### ISSUE TITLE
Incomplete transaction history

### ISSUE THREAD

**Issue by hubikj** [mycelium-com/wallet#279]
Try adding this address: [1HxKsiHMWNDZGfoFV1Bs9o9FHjVmy8BY2L](https://insight.bitpay.com/address/1HxKsiHMWNDZGfoFV1Bs9o9FHjVmy8BY2L)
It should have 253 transactions quite regularly since March 20, but it only shows transactions from March 20 to March 30 plus 2 most recent transactions from yesterday and today. The balance is correct.
I would understand if it loaded, for example, only 50 most recent transactions, but this is very confusing.

**Comment by Giszmo** [comment]
Can confirm the transaction list looks weird on Mycelium. It shows only 30 something of the more than 200 transactions that block explorers find.

**Comment by DanielWeigl** [comment]
Hi, this is a known bug. The sync does not fully download all transactions after a restore, if they are not relevant anymore for the total balance. Only transaction leading to unspent outputs (UTXO) and their direct parent transactions are fetched.

It is something we wanted to fix but hadnt had the time so far. Not sure if we will fix it before the new wallet arrives which has a completely different sync algo. wontfix in the meantime
