### ISSUE TITLE
Encrypted PDF Backup problem

### ISSUE THREAD

**Issue by ashnikel** [mycelium-com/wallet#28]
HTC Legend
Android 2.2
Kernel 2.6.32.17-g30929af
Mycelium 1.1.2

Application crashes on "Encrypted PDF Backup" page. "Preparing encryption key... 0%" message appears and then oops (report sent). What additional info can I provide?

**Comment by Giszmo** [comment]
I assume this is fixed. Feel free to re-open if not.
