### ISSUE TITLE
Sending amount discrepancy: Balance- and Transactions-tab

### ISSUE THREAD

**Issue by trebormag** [mycelium-com/wallet#280]
Scanned QR Code to pay 10€.
After sending the transaction it showed the wrong sending amount at the balance-tab.
(0.01126...BTC, 6.61 EURO instead of 0.01761...BTC, 10.33 EURO)
But the total Balance and the transaction at the Transaction-tab is correct.

![20160628_mycelium](https://cloud.githubusercontent.com/assets/9282957/16404909/6a35b80c-3d03-11e6-8f83-fb679170c752.jpg)

@DanielWeigl : Liebe Grüße vom Herr Siegfried :-)
Fallst du von mir mehr details zu der transaktion brauchst, einfach melden.
LG Gü

**Comment by trebormag** [comment]
Update: The "wrong" sending amount shown is exactly the "10€" sending amount minus the the 0.00634987BTC change from the previous transaction.
BUT this previous transaction already had 6 confs and "green" light. see picture.

![dsc_0214](https://cloud.githubusercontent.com/assets/9282957/16405318/fd52c30c-3d06-11e6-80cd-6fe80afc67f5.JPG)

Was really confusing because first we thought Herr Siegfried entered a wrong Euro amount.

**Comment by DanielWeigl** [comment]
Hi Gü, thx for the report. Could you share the txid with us? Either here or to developers@mycelium.com. Ill look into it and see if i can reproduce it.

**Comment by DanielWeigl** [comment]
Hi,

that bug is now fixed in the current release (2.8.4) - there was a bug in the synchronization, which missed to remove spent UTXOs from the internal database
