### ISSUE TITLE
BIP72 is not fully supported

### ISSUE THREAD

**Issue by ondra-novak** [mycelium-com/wallet#286]
According to [BIP72](https://github.com/bitcoin/bips/blob/master/bip-0072.mediawiki), there are two ways how to use payment protocol specification with **bitcoin:** protocol.

> "If the "r" parameter is provided and backwards compatibility is not required, then the bitcoin address portion of the URI may be omitted (the URI will be of the form: bitcoin:?r=... )."

However:

this example works (Mycelium opens payment form)

![backwards](https://cloud.githubusercontent.com/assets/96378/17461777/3e89d1fc-5c98-11e6-8b02-31eabb9330e1.png)

`bitcoin:mq7se9wy2egettFxPbmn99cK8v5AFq55Lx?amount=0.11&r=https://merchant.com/pay.php?h%3D2a8628fc2fbe`

this example show only error message "unrecognised format"

![paymentprot](https://cloud.githubusercontent.com/assets/96378/17461778/48492e4a-5c98-11e6-898b-6f1ebfe13178.png)

`bitcoin:?r=https://merchant.com/pay.php?h%3D2a8628fc2fbe`

For some reason, i need to avoid backward compatible way. Users without payment protocol support will not use my software.

Used 2,8,4-TESTNET

**Comment by Giszmo** [comment]
I'm slightly surprised that the fallback option with the dummy url even works at all. According to BIP72 in presence of an `r=` parameter, the address should be ignored, right?

Else I agree with OP that this needs investigation. I verified with a fresh payment request from bitpay:

![bitpay](https://cloud.githubusercontent.com/assets/96378/17461844/f8de79d0-5c99-11e6-9152-ced13f3d851f.png)

`bitcoin:?r=https%3A%2F%2Fbitpay.com%2Fi%2FRoF6EUSN1hqQ2oUUoJxzqd`

and came to the same result.

**Comment by Giszmo** [comment]
issue found and fixed with next release
