### ISSUE TITLE
Payment request claim wrong amount when right 

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#287]

**Comment by Transisto** [comment]
.

**Comment by Giszmo** [comment]
When using the "receive payment" dialog and the other sends exactly the right amount, the receiving Mycelium gives a warning.

![25d571ff-e747-4ac6-a013-c08acd11cf40](https://cloud.githubusercontent.com/assets/96378/17491224/fbbeeae6-5da6-11e6-84c5-17a0a6b3f33e.jpg)

**Comment by Giszmo** [comment]
issue found and fixed by @DanielWeigl
