### ISSUE TITLE
I recover my Mycelium wallet /how do i get my private btc adress key for selling my btc

### ISSUE THREAD

**Issue by BitcoinBelieverxxx** [mycelium-com/wallet#291]
I finally recoverd my Mycelium wallet, i see the good balance and all transactions till this day.
But if i want to sell ( when i click Sell ) he asked ' you need Private key to make a sell ?
Wich wallet key do i have now..and how do i get my private adress key what belong to my wallet ?
Tell me where and how i do that, because i want to sell my Bitcoins as soon as possible !

**Comment by BitcoinBelieverxxx** [comment]
I finally recoverd my Mycelium wallet, i see the good balance and all transactions till this day.
But if i want to sell ( when i click Sell ) he asked ' you need Private key to make a sell ?
Wich wallet key do i have now..and how do i get my private adress key what belong to my wallet ?
Tell me where and how i do that, because i want to sell my Bitcoins as soon as possible !

**Comment by DanielWeigl** [comment]
Hello,

how did you restore your wallet? Do you have the master seed backup (=12 words) from your original wallet?

Follow this instructions to restore from your backup
http://support.mycelium.com/hc/en-us/articles/206335729-How-do-I-restore-a-backup-

**Comment by Giszmo** [comment]
no reply in a week. closing.
