### ISSUE TITLE
Include link to TREZOR Manager when uninitialized TREZOR is attached

### ISSUE THREAD

**Issue by prusnak** [mycelium-com/wallet#292]
Could we include link to TREZOR Manager app when uninitialized TREZOR is attached?

Mycelium now shows dialog with "Device not initialized", but it would make much more sense to point users to TREZOR Manager app, so they could setup their devices.

Link to store: https://play.google.com/store/apps/details?id=io.trezor.app

If the app is already installed, it would be great if Mycelium could just start it.

PS: TREZOR Manager already links to Mycelium as can be seen [here](https://lh3.googleusercontent.com/Ht6wRFlBChquwRbM7USHjW-1jhGssDJ_VnVt3uv6pmORf2u0wdo2qEX3DNm8Ma_qOw=h900-rw)

// cc @slush0

**Comment by DanielWeigl** [comment]
Will be in the next update. (For initialization and for firmware updates)

Thx for linking to mycelium! :)
