### ISSUE TITLE
Add support for TREZOR v2

### ISSUE THREAD

**Issue by slush0** [mycelium-com/wallet#293]
Hello Mycelium team,

please add support for USB device with VID 0x1209 / PID 0x53C1. TREZOR v2 supports TREZOR v1 protocol, so everything should work the same as when using VID 0x534c, PID 0x0001; no changes in application logic, communication protocol or changes in UI are necessary.

**Comment by FrancisPouliot** [comment]
+1

**Comment by DanielWeigl** [comment]
Added the ID for trezor, will be in the next update.
Were you already able to test it against (a self compiled with changed VID/PID) mycelium?

just out of curiosity, why is it a different VendorID and a strange ProductID?

**Comment by slush0** [comment]
Thanks for quick addition. We can test it against Mycelium, althought we did not do it yet. However, our basic premise is to "stay compatible with Trezor v1 proto", so any incompatibility will be definitely bug on our side, not in Mycelium.

VID / PID is allocated thanks to project http://pid.codes.

**Comment by DanielWeigl** [comment]
Ive just compiled a testnet build with the new IDs: https://wallet.mycelium.com/download/testing/mbw-prodnet-release-2.8.4-trezorV2build28407.apk

Please report back if it works, thx

**Comment by jonathancross** [comment]
@slush0 Any updates?

**Comment by Giszmo** [comment]
This was fixed a year ago. Mixed it up with segWit, which is a newer bug.
