### ISSUE TITLE
Some content descriptions read as "an icon"

### ISSUE THREAD

**Issue by tspivey** [mycelium-com/wallet#297]
Using the receive screen as an example and following along in the XML:
1. The QR code on this screen reads as "an icon" (android:contentDescription="@string/an_icon"). I think this would be better as "QR Code".
2. The button after optional amount reads as "an icon". It might be better as "Enter Amount".
I also notice this in other places, for example the Balance tab on the main screen.

**Comment by Giszmo** [comment]
Thank you for reporting this. I suggest to group those issues in just one. I'll recycle and update #296 accordingly.
