### ISSUE TITLE
Support for Ledger Nano S

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#299]
Is it supported ? I can't make it work.

According to Ledger it should be easy for you to make it work.
https://www.reddit.com/r/Bitcoin/comments/4oyylt/ledger_nano_s_new_generation_hardware_wallet/d4hpwkc

**Comment by Transisto** [comment]
.

**Comment by Giszmo** [comment]
This might be a question for @LedgerHQ

**Comment by Transisto** [comment]
.

**Comment by btchip** [comment]
It'll be done soon. A Nano-S has also been sent to Daniel for tests.

**Comment by djpnewton** [comment]
looks like PR #301 needs testing/merging
