### ISSUE TITLE
Chat dropping messages

### ISSUE THREAD

**Issue by kilorat** [mycelium-com/wallet#302]
If there's a better place to report this, please let me know.

It started for me 12 hours ago, and has not improved. Is there an issue with the servers? I tried several different internet connections, and everything else is working from my phone.
I'll write a message, and it doesnt even display it to me. If I fully close the app, recent messages in chat won't display, but after some minutes it catches up and shows the whole chat. Many times what I write never makes it to the other person at all, it's not merely slow.

**Comment by DanielWeigl** [comment]
Hello kilorat, our localtrader backend was out of free connection handlers. After restart its no available again.

Im not completely sure what locked it up, but ill monitor it more closely and try to find the issue.

**Comment by kilorat** [comment]
I just gave it another try, it's still doing it.

**Comment by DanielWeigl** [comment]
Are you using tor/orbot or are you directly connected?

**Comment by kilorat** [comment]
directly connected. It was usually reliable over the years I've been using it, just lately it's been hit or miss. Today is much better though, it hasn't dropped anything. If there's no problems on the servers now, then I'm not going to worry about it.

**Comment by DanielWeigl** [comment]
also just gave it a try and messages appear immediately on the other phone (in both directions) - is it still slow for you? Do you have a normal android setup or is it a phone without google services? Then the GCM notification wont work and LT relies on continuously polling - which usually feels slower.

**Comment by kilorat** [comment]
I use a normal un-jailbroken phone on a normal network, it's not on my end, the person I was chatting with noticed the same problem. I tried both wifi and LTE, it wasn't any better on LTE. This was before the connection handlers thing you fixed by restarting. After that, I was only able to chat once, and the other person didn't reply. it took 10 seconds for my message to display for me.
I have to wait for the next trade before I can know how well it's working now.

**Comment by Giszmo** [comment]
This sounds flaky and hard to reproduce. Mind if I close it for now? If it is only a 10s delay, it should be ok. If messages drop, then not so much but without further information we can't really do much.
