### ISSUE TITLE
Request: New Exchange Source itBit

### ISSUE THREAD

**Issue by SkillfulHacking** [mycelium-com/wallet#303]
I would like to see itBit prices in the Exchange Sources option.

**Comment by Giszmo** [comment]
How would I know the relevance of this exchange? Never came across it.

**Comment by SkillfulHacking** [comment]
http://data.bitcoinity.org/markets/exchanges/USD/24h#rank_desc

Currently ranked 2-3 overall in US markets depending upon which factors you rank them on, higher than some of the others already listed.  Thanks.

**Comment by Giszmo** [comment]
yeah, I see now. Hmm. Probably relevant then and rather easy to add. Will propose it.

**Comment by Giszmo** [comment]
It's a pull request on our internal repository now.

**Comment by DanielWeigl** [comment]
Is merged and available in your wallet now
