### ISSUE TITLE
Show amount in Sat./Bytes under fee priority selection

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#304]
Would be good to know when trying to figuring out whether :
A. My transaction is about to spend many small inputs.
B. The network is over-saturated.
C. Mycelium fee calculation is buggy.

**Comment by Giszmo** [comment]
As seen in #311, the fee fluctuation can be very dramatic, especially for the priority option.

Already prior to entering details that allow to calculate the absolute fee, I suggest to display a fee for a 400B transaction and the sat/B and make it big, fat and white on red if that fee is more than 50% above the user's last fee(s) in either absolute (once details are provided, as here the user might revert to normal fees if he hits on this once-in-a-while huge transaction he makes) or relative terms.

**Comment by Giszmo** [comment]
I think this is done.
