### ISSUE TITLE
Spurious Trezor firmware notification

### ISSUE THREAD

**Issue by wirion** [mycelium-com/wallet#305]
As noted [here on Reddit](https://www.reddit.com/r/TREZOR/comments/58p4p4/trezor_new_firmware_in_mycelium/), Mycelium 2.8.5 on Android is complaining about Trezor's firmware not being up to date, even though 1.4.0 is currently the latest firmware.

**Comment by DanielWeigl** [comment]
yes, thats a bug in our version check - is fixed internally and will be in the next update. Thank you for reporting it.
