### ISSUE TITLE
Autofocus not working on Samsung Galaxy Note

### ISSUE THREAD

**Issue by andreasbuhr** [mycelium-com/wallet#31]
Hi there,

I am unable to use cold storage because I cannot scan the QR codes. Because the autofocus is not working on my Samsung Galaxy Note. I tried enabling and disabling autofocus in the settings, but this seems to affect the brightness, not the autofocus. With autofocus disabled, the image is almost only white. With autofocus enabled the brightness is ok, but no focus. Currently I scan the QR code with another app, then save it to the clipboard and use it from there in Mycelium.

Can I help in fixing this? If there is anything I can to please let me know.

Best,
Andreas

**Comment by Giszmo** [comment]
This issue should be fixed meanwhile. feel free to re-open.
