### ISSUE TITLE
[Bug] [High Priority] 1724 satoshi / byte fee suggested by "Priority" fee setting.

### ISSUE THREAD

**Issue by dabura667** [mycelium-com/wallet#311]
https://www.reddit.com/r/Bitcoin/comments/5bfvef/wtf_is_up_with_mycelium_fees/

The transaction in question:

https://live.blockcypher.com/btc/tx/91a9c588ed5a3ebcd394a48067cc94cdcf7c37cb558b930d6e2c7eec94262b3f/

Idea: I think this has to do with bitcoind estimatefee returning -1 when there is not enough data to estimate the targetted block speed.

**Comment by DanielWeigl** [comment]
Hello,

Thanks for notifying us. We are relying on BitcoinCore for the fee estimation, and it seems the current Mempool has a lot of high-fee transactions in it, which makes the "next block"-fee estimation so high.

Use the "normal" fee level and you should get a reasonable fee. If you really want to be (with a high probability) in the next block, you currently need to pay a that high fee.

Here is a different reddit post with some explanations in the comments: https://www.reddit.com/r/Bitcoin/comments/5bizrb/1block_confirmation_fee_estimates_are_absurdly/

**Comment by Giszmo** [comment]
I put it invalid/won't fix as it seams to be an upstream issue or a (hopefully temporary) attack.

There are other issues that fall into the same category "protect the user from surprising stuff" but as Daniel said, if you want priority treatment, to the best of our knowledge, this was the fee you had to pay.

**Comment by Giszmo** [comment]
Lets address this issue in #304 , as the sat/byte fee can be known long before hitting send, while the absolute fee normally depends on amount (and recipient).

**Comment by Giszmo** [comment]
@DanielWeigl deployed a "temporary" hack. Priority transactions are now the average of one and three block target.
