### ISSUE TITLE
Tor connection not working Andorid 

### ISSUE THREAD

**Issue by Onefox** [mycelium-com/wallet#315]
Since some weeks the tor integration barely works.

I will get the error no server reachable or the endless spinning circle above the tor symbol.
In the bottom it says Tor init and v2.8.5.
The android tor browser works. At the moment i am in a WLAN network.

I use Android 6.0.1/ OxygenOS-Version 3.1.0.
With an One plus 1 Phone. The phone is not rooted.

Is there a way to grab a log file that could be useful for you guys?

**Comment by DanielWeigl** [comment]
This is related to #288 . Since android 6.0 you need to start orbot manually. We might be able to fix it in the next few weeks, but its not top prio right now.
