### ISSUE TITLE
BIP39 restore fails with non ascii characters passphrase

### ISSUE THREAD

**Issue by Y75QMO** [mycelium-com/wallet#317]
The addresses generated by Mycelium after trying to restore the following BIP39 are incorrect:

**24 words:** helmet brisk decorate dose mother spray swim surround sauce lizard first hockey talent gloom curtain submit fat average enter glue equip post scrub priority

**Password**: ñolyutg.34rhy43sf

First address according to BIP39 is: 13KKeUtn2B1Xy7gQjUCw6PMC2yi1XxbevK
Address generated by Mycelium is: 1GMYPj3Jjdg1bKk9YdUpA2tvwFf3YNXeaP

**Comment by Giszmo** [comment]
Thanks for reporting. We have to look into this.

**Comment by Giszmo** [comment]
According to [this tool](https://iancoleman.github.io/bip39/), OP's wallet would be `xprvA1LR897SzFJnhPTUgzYnZs2bxCZsynSVu6G42E7Vzej8ebRCZcU4gAuX2w3JgPwFcXFC2dRveujiHyHRassZp3m58JfdwRURCa2eyB3NbiF`.

**Comment by Giszmo** [comment]
our implementation skipped the NFKD normalization of UTF8 strings mandated by [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki).

**Comment by Giszmo** [comment]
has been merged and will be fixed in our next update
