### ISSUE TITLE
Economic fee is huge compared to Normal 

### ISSUE THREAD

**Issue by leighman** [mycelium-com/wallet#318]
I have my default fee level set to Economic

Send -> Scan QR code -> Enter 10 USD

Economic fee: 4971 bits
Normal fee: 181 bits

Android 4.1

**Comment by vnnkl** [comment]
Hi,

not for me, are you running the latest version of the wallet?

a regular transaction (1 input, 2 output) will result in these fees for me atm,
13489 sat Low-prio
14389 sat Eco
18125 sat Normal
21580 sat Priority

Did you check the utxos of your account, can it be related to that?

**Comment by DanielWeigl** [comment]
This might be some effects of coin-selection. Can you show us your unspent outputs (Account Screen, select account -> menu -> show unspent outputs)

It might be, that the (sending amount + low fee) is satisfy able by the first `n` unspent outputs -> transaction uses them all. If (sending amount + higher fee) means the first `n` arent enough and the `n+1`''th unspent is big enough to cover it all, then only one input is used -> lower fee.

**Comment by leighman** [comment]
I went with Normal in the end. That transaction has 1 input.
The account does have lots of unspent outputs of ~40-100bits so that does sound likely.
Thanks.

**Comment by DanielWeigl** [comment]
Yes, definitely confusing and we need a better examination of the fee and the built transaction (a "Details..." button that shows which inputs are used, how many bytes, what fee per byte, ... etc), we will put it on our (already way too long) todo list

**Comment by reinier1991** [comment]
jsjs

**Comment by Giszmo** [comment]
We might close this with #304 
Maybe for really having it fixed we might have to show both sat/B and total bytes.

**Comment by Giszmo** [comment]
sat/B and size are shown now.
