### ISSUE TITLE
"unrecognized format" when scanning cryptopay.ninja payment request

### ISSUE THREAD

**Issue by zundg** [mycelium-com/wallet#319]
Just tried to pay something with bitcoin, they showed me some request by cryptopay.ninja. When trying to scan this mycelium toasted me "unrecognized format".
![screenshot from 2016-12-19 20 56 23](https://cloud.githubusercontent.com/assets/5032145/21327070/a80ccdb0-c62d-11e6-8082-97efad82b7d2.png)

**Comment by DanielWeigl** [comment]
Hello,

the QR-code decodes to `1E3vxivigovBy7pxg9RtU15fNkFJZKiEyd?amount=0.07918592` - but [BIP21](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki) requires bitcoin URIs to have a `bitcoin:` prefix - please contact the website owner to fix his payment requests/QR-codes.
