### ISSUE TITLE
Encrypted backup dump

### ISSUE THREAD

**Issue by Tyler-Hardin** [mycelium-com/wallet#323]
Hi, I'd really like to have this feature, the ability to dump private keys under suitable encryption. I'm surprised it doesn't exist in the app already. Are the maintainers against including the feature, or is just a matter of having better things to work on? I wouldn't mind doing it myself, but would prefer it end up in the main repo.

**Comment by vnnkl** [comment]
Hi Tyler, 
do you mean of specific addresses of your HD seed or do you mean similar to encrypted PDF backups of single address accounts as described here (http://support.mycelium.com/hc/en-us/articles/207045495-What-about-previous-backups-Do-my-old-ones-still-work-)?

**Comment by Tyler-Hardin** [comment]
I mean an encrypted backup of the HD seed itself. I'm looking for an
alternative to the "paper wallet" style backup that is currently required
to set a PIN. I'd like to add a "dump HD seed to encrypted file" option in
that dialog.

**Comment by Giszmo** [comment]
We had it that way (kind of) before HD wallets were a thing and I don't see how adding such a non-standard feature would be a thing to do.

There is however a standard that we only support partially. [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) allows for an optional passphrase. Mycelium doesn't allow to set a passphrase when creating a new wallet but you can restore such a backup with passphrase. Hope that helps.
