### ISSUE TITLE
Hide letters that are not valid for the current mnemonic word

### ISSUE THREAD

**Issue by Giszmo** [mycelium-com/wallet#326]
In the mnemonic phrase entry, valid words strongly limit which are valid next letters even after entering the first letter. Hiding or graying out invalid letters could speed up entry.

**Comment by Transisto** [comment]
Good idea.

**Comment by fortran77** [comment]
I've been testing the Electrum wallet for Android, on which the keyboard blanks out letters not valid as the next letter. I find it disorienting and confusing. Like most of us, I am used to navigating a qwerty keyboard based on the key layout. Having most of the keys hidden causes me to get confused about where I am.

Maybe slightly dimming or greying the invalid keys won't be so disorienting. Or maybe not — a lifetime of practice with keyboards is hard to undo. It should be easy to grab a few friends and neighbors and see which type of keyboard yields better results. I predict that that dimming or blanking invalid keys will not yield any noticeable improvement in real-life tests.

**Comment by Giszmo** [comment]
This will be subject to a "new UI".
