### ISSUE TITLE
mycelium blockonomics p2p invoicing integation

### ISSUE THREAD

**Issue by shivaenigma** [mycelium-com/wallet#329]
Hi,

This is to get clarification on how to implement blockonomics integration. I couldn't find development docs on how to develop plugin for integration

Basically here is how this is will work:
- User goes to receive tab
- Will click on button 'create p2p invoice' 
- This is launch url `https://www.blockonomics.co/invoicecreate/#/?addr=<address>`
- Enter details including description, amount in any currency
- Shares invoices with payee.

More details on working [here](https://medium.com/@blockonomics_co/peer-to-peer-no-signups-invoice-in-fiat-get-paid-in-bitcoin-f77772e4308b#.2no6tcdgj)

Would appreciate if someone can guide me on the feasibility of this/how I can go forward implementing this in mycelium code.

**Comment by Giszmo** [comment]
Sorry, this sounds like an optional feature for our new wallet if at all.

**Comment by Giszmo** [comment]
I assume you are contacting us from blockonomics, hoping for an integration in the Mycelium wallet? If so, the way to go would be to write us an email and get in touch with management to talk about revenue sharing and implementation costs.
