### ISSUE TITLE
After entering 11 seed words, checksum error no prompt for 12th word

### ISSUE THREAD

**Issue by fortran77** [mycelium-com/wallet#332]
This is one-time-only, not reproducible situation.

After a fresh install of Mycelium 2.8.6 on Android 5.1, on the initial screens I requested a restore with seed 12 words, no passphrase. Then I proceed to enter the seed words.

I made a few typographical errors, and corrected them with backspace and/or “Delete last word” in some sequence that I do not recall.

After I had entered 11 words, the screen reported a checksum error, and did not prompt me to enter the 12th word.

I examined the list of 11 words that had been entered so far, very carefully, and they were correct.

Puzzled, I tapped on “Delete last word”. Now the screen showed a list of 10 words as expected, and the prompt read “enter word number 11 of 0” (not the usual “enter word number 11 of 12”).

So I entered the 11th word and again saw the screen with the checksum error, and no prompt to enter the 12th word.

Even though I was not prompted for the 12th word, I proceeded to enter it on the keyboard. It was accepted and the wallet correctly initialized itself and showed the expected transactions and balance. So this means that the words that I had entered were correct.

To see if this is a reproducible bug, I wiped the app's data in the Android settings screen, and followed the same procedure as above. This time I was prompted for the 12th word as usual. I repeated this wipe-and-re-enter sequence a second time and again did not observe any misbehavior.

So this appears to be an intermittent bug.

Since the word list belongs to a real wallet, I won't post it here.

**Comment by Giszmo** [comment]
Thanks for reporting this. It seams like a very rare bug. I just tried some things in line with what you described but can't provoke a miscount, neither.
