### ISSUE TITLE
Hangs at start-up logo (trivial bug)

### ISSUE THREAD

**Issue by fortran77** [mycelium-com/wallet#336]
Minor bug.

When I invoke Mycelium, it gives me the Enter PIN Code prompt. At this point, suppose I change my mind and try to exit with the back button. That is ignored, so I then exit with the home button.

Now if I invoke Mycelium again, it gives me its logo screen, and hangs at that screen. It stays there until I touch the screen, and then I get the Enter PIN Code prompt.

If I don't touch the screen, but simply exit the logo screen with the home button, and invoke Mycelium again, it again gives me its logo screen, and hangs at that screen in the same manner.

If I exit the logo screen with the back button, then on the next invocation Mycelium behaves normally and gives me the Enter PIN Code prompt as expected.

Using Mycelium 2.8.6. Same behavior on Android 5.1, 6.0.1, and 7.1.1.

**Comment by Giszmo** [comment]
thanks for reporting

**Comment by feelfreelinux** [comment]
@Giszmo I fixed this issue in https://github.com/mycelium-com/wallet/pull/384

**Comment by Giszmo** [comment]
Thanks. The fix will be deployed in one of the next releases.
