### ISSUE TITLE
Integrating Ethereum with Mycelium mobile wallet? Where do we stand?

### ISSUE THREAD

**Issue by Nogreedy** [mycelium-com/wallet#337]
Hello,
https://www.reddit.com/r/ethereum/comments/4gojnu/mycelium_mobile_wallet_will_implement_ethereum/
https://www.reddit.com/r/Bitcoin/comments/4gkxox/mycelium_new_wallet_announcement/
Who is in charge of integration?
Are you in contact with Ethereum devs teams ?
Thanks in advance for your answer.
PS : my question is specifically about Mycelium wallet... I know there are others ETH mobile wallets (Jaxx...) but I prefer Mycelium and I'd like to use Mycelium with Ethereum...

**Comment by sp4ce** [comment]
Hello do you have any update on this?

**Comment by Giszmo** [comment]
We hear you but at this point there is no quick integration in sight.
