### ISSUE TITLE
Add more exchange rate source indecies

### ISSUE THREAD

**Issue by 4NobleTruths** [mycelium-com/wallet#344]
Please add another exchange rate index.

Right now, you only have one - BitcoinAverage. You've integrated with them years ago, but they never reciprocated, and don't integrate with your API or your data.

My choice for a second would be BraveNewCoin.

**Comment by johnzweng** [comment]
Right now they have already many more than just Bitcoin Average available (but not BraveNewCoin). You find it in settings: 

![mycelium_exchanges](https://cloud.githubusercontent.com/assets/285900/24236791/b0d59d2c-0fa3-11e7-92bb-1f5f2bf46f21.jpg)

**Comment by 4NobleTruths** [comment]
Thank you. Right now, all but BitcoinAverage are particular exchange feeds.
BitcoinAverage is the only index.

**Comment by Giszmo** [comment]
Well ... any special wishes? Merge requests welcome

**Comment by jonathancross** [comment]
FYI: BNC looks good, but is a bit more expensive.

* **BraveNewCoin** pricing:
https://market.mashape.com/bravenewcoin/digital-currency-ex-rates/pricing

* **BitcoinAverage** pricing:
https://bitcoinaverage.com/en/plans
