### ISSUE TITLE
Feature request: Allow deletion of first account

### ISSUE THREAD

**Issue by fortran77** [mycelium-com/wallet#347]
It should be possible to delete the first account that was created in Mycelium. Use cases are discussed below.

1. Suppose we are using a hardware wallet, and wish to use only that. Keeping the first account around, which does not support any hardware wallet, is superfluous and visually distracting and may encourage accidental use.

2. Suppose we want to use Mycelium in a receive-only role, by importing a master public key on the Advanced screen. Again, as above, the first account is superfluous/distracting/etc.

3. Suppose we have some other software wallet, and wish to quickly import one or more accounts from it, by scanning master private keys. Since the first account requires seed words and does not support scanning master private keys, as above it is superfluous/distracting/etc.

The above situations are easily addressed by allowing deletion of the first account. There are various ways of protecting naive users from deleting an essential account. One possibility would be to make creation of the first account optional, i.e., start Mycelium with an empty list of accounts, and guide the user into creating or restoring the first one. Alternatively, Mycelium could proceed as it does now, by requiring the first account to be created with seed words, but allow deletion of the first account where at least one other account exists and the first account has never received any funds.

Issue #127 from some years ago may be partially relevant here. Things have changed a lot since then.

**Comment by Giszmo** [comment]
Noted but I doubt this will ever happen as the main HD account is used for so much more than just the bitcoin wallet. For example I would love to extend it to store meta data in storJ or similar, automatically, encrypted in the background.
