### ISSUE TITLE
Newest Android update broke Mycelium's ability to use location services

### ISSUE THREAD

**Issue by kilorat** [mycelium-com/wallet#348]
I don't have a 2nd phone to test with, but this is what I'm seeing on mine. I don't jailbreak or anything like that, I'm pretty boring with my phone.
I got a notification that the OS needed updating, but after updating, I get this if I try to press the button in Mycelium to set the location to my current location:

![screenshot_20170412-104059](https://cloud.githubusercontent.com/assets/441462/24971584/518eb270-1f6d-11e7-9d4b-a70e2b1e4022.png)

Google maps works, so GPS is working.
I can type in an address and set the location, and that works perfectly.
If I go into location services, it looks like it doesn't even see Mycelium trying to access it:

![screenshot_20170412-104047](https://cloud.githubusercontent.com/assets/441462/24971611/66219ba8-1f6d-11e7-8235-6612b1565809.png)

Here's the versions my phone is at:

![screenshot_20170412-104322](https://cloud.githubusercontent.com/assets/441462/24971624/6f23a73c-1f6d-11e7-8112-90e383571d38.png)

I am making an assumption that it's related to the update, because its the only recent change I made to my phone. I haven't tried to set the location in at least a few months.

**Comment by kilorat** [comment]
After an hour or so this magically started working. I should have given it more time!

**Comment by Giszmo** [comment]
Weird. Thanks for reporting and closing :)
