### ISSUE TITLE
I cannot spend from an specific address in HD Wallet 

### ISSUE THREAD

**Issue by stupidcache** [mycelium-com/wallet#352]
Hi, every single address on my HD wallet contains differents quantitys of bitcoins, for example:

0,1
0,9
1
1
3,2
0,1

Then, i decided to send 3 btc. instead taking 3 btc from the address with 3,2 takes 0,1+0,9+1+1 or something like that.

I think mycellium should allow a quick browsing that shows address that match with the amount that i want to send in order to avoid big fees and also contributing to reduce the flood in the blockchain .

thanks and sorry for my poor english

**Comment by Giszmo** [comment]
"Coin control" is not a planned feature for the near future. Please note that other considerations than just the transaction size have to be considered. The wallet should prefer to spend confirmed outputs, historically it had a preference for "old" coins, which is not very relevant anymore, ideally it should spend all outputs of one address together for privacy reasons and ideally it should reduce the UTXO set, which is what Mycelium does not at all at the moment, resulting in long-time users being surprised when they get to spend the last coins from an account, with the coins being in 300 UTXOs.
