### ISSUE TITLE
When no connection to fee data mycelium use extremely low value and doesn't warn the user. 

### ISSUE THREAD

**Issue by Transisto** [mycelium-com/wallet#353]
25, 36, 65 and 600sat/byte are the default values. 

Urgent, causes stuck transactions

**Comment by Giszmo** [comment]
This sounds bad! Thank you for reporting. We have to look into this immediately.

**Comment by Giszmo** [comment]
So the default values were always set to some historic high + x, which is kind of not ok, especially as those are the default values if the fee rates couldn't get updated for 2h. I'm working on changing this to persist fee rates and use it regardless of age of the data, with a warning toast if it is older than 2h.

**Comment by Giszmo** [comment]
The default values were put up to date. A mechanism that uses the last value even across sessions and warns the user still has some seamingly unrelated crash bug. Closing for now.
