### ISSUE TITLE
mycelium freezes and then crashes after I enter the sixth digit of the pin

### ISSUE THREAD

**Issue by celestialboner** [mycelium-com/wallet#354]
Steps taken are:
1. Open the app
2. Press any button combination that would lead to the prompt to enter the pin
3. Enter my pin and on the last digit the app freezes and then I get the "mycelium is not responding do you want to close it" prompt with the options to report wait or OK

This problem started after I forgot my pin and entered incorrect ones about 50 or so times and now I know the correct one but the app will freeze after I enter it

Android 6.0.1
Mycelium 2.8.9

Thank you.

**Comment by Giszmo** [comment]
what happens if you hit "wait"? it intentionally does give you an ever increasing waiting time but obviously it's not supposed to crash doing so.
If i remember right, it will not check if the pin is right until the delay is over, so even the right pin should impose a last wait on you.

**Comment by Giszmo** [comment]
You killing your app is not the same as the app crashing. Just hit wait. And yes, inconvenience is the purpose of this delay, for the wallet's security.

**Comment by fhlr83** [comment]
I'm passing by the same problem... After set the pin code the wallet opens and crashs... I haven't the option to wait. It jist stop and kill the process.
