### ISSUE TITLE
How to build backuputil?

### ISSUE THREAD

**Issue by segdy** [mycelium-com/wallet#356]
What is the correct way to build backuputil?

After downloading 2GB worth of Android SDK, Java JDK etc I managed to compile mycelium itself using `gradlew build` and I get the apk files. However, it seems this flow does not touch backuputil at all.

I tried `gradlew build` in the backuputil directory but it fails:
```
* What went wrong:
A problem occurred evaluating project ':backuputil'.
> Project with path ':public:bitlib' could not be found in project ':backuputil'.
```

I tried using `javac` directly but it lacks all the dependent libraries.

Different combinations of `gradlew` with `backuputil` in the main directory fail too.

**Comment by segdy** [comment]
Eventually I managed to do this. I think there should be the following changes:

1.) settings.gradle should contain

`include "backuputil"
`

2.) In `backuputil/build.gradle`,

`compile project(':public:bitlib')`

should be changed to

`compile project(includePrefix +':bitlib')
`

**Comment by Giszmo** [comment]
ok. I'll change that. Good point. Never had paid attention to the backup tool at all. Is it referenced somewhere?

**Comment by segdy** [comment]
Thanks. I found only very vague references. Unfortunately and surprisingly I seem to be the one person on earth who still wants to access an (older) backup.

For example, it's referenced here: http://support.mycelium.com/hc/en-us/articles/207045495-What-about-previous-backups-Do-my-old-ones-still-work-

I would even more appreciate if the jar file (or the zip file) would be provided on the website (which used to be the case according to some forum post)

**Comment by Giszmo** [comment]
Well, I guess it's more a pointer to the open nature of Mycelium. You don't have to use the wallet and if you do, you can compile it yourself and if you don't have an android phone, you can use just any computer. But I will add the changes you suggested.
