### ISSUE TITLE
high fee

### ISSUE THREAD

**Issue by nkkko** [mycelium-com/wallet#357]
please check the img [![IMG_0468.jpg](https://s22.postimg.org/le3o8bg5d/IMG_0468.jpg)](https://postimg.org/image/4qc65tldp/)

**Comment by nkkko** [comment]
Fee per byte	1,956.204 sat/B ?!?

**Comment by Giszmo** [comment]
Where did that happen? is that the Android Mycelium Wallet?

**Comment by nkkko** [comment]
Hi, it was on iOS wallet.

**Comment by Giszmo** [comment]
was iOS
