### ISSUE TITLE
Displaying message from Bitcoin URI

### ISSUE THREAD

**Issue by phplego** [mycelium-com/wallet#36]
When we send new Intent from other app there is one optional parameter "message" in the URI. But it is not displayed in Mycelium wallet (Coinbase app, for example, displayed it properly).

```java
// I mean this "message" parameter in uri:
URI uri = Uri.parse("bitcoin:1FfZBhs...?message=Donation")
Intent intent = new Intent(Intent.ACTION_VIEW);
intent.setData(uri);
startActivity(intent);
```

**Comment by Giszmo** [comment]
this has been fixed meanwhile
