### ISSUE TITLE
Trezor Firmware 1.5.0: address in change output

### ISSUE THREAD

**Issue by jhoenicke** [mycelium-com/wallet#366]
The latest firmware of Trezor does some extra sanity checks that triggers a bug when used with mycelium.  To reproduce, just update to firmware 1.5.0 and send some transaction that requires a change output. 

The problem is that Trezor no longer allows to give both a bip-32 path and the base58-encoded address in the change output.  The reasoning was, that if they were different this could lead to an attack if one part of the code used the base58 address to create the output.  I was not aware at the time that there is a wallet that sets both fields.

To fix mycelium don't set the address field in the change output only the address_n field.  The address field in change outputs was ignored by older firmwares anyway.

**Comment by jhoenicke** [comment]
Feel free to ask questions if my description was too terse.  But it basically boils down to moving this line:

https://github.com/mycelium-com/wallet/blob/0f85b8a8ba497158e5ad0c88c388937a62a4bd05/mbw/src/main/java/com/mycelium/wallet/extsig/common/ExternalSignatureDeviceManager.java#L363

to a new else part of the following if, so that the address is not set for change addresses.

**Comment by prusnak** [comment]
Fixed in https://github.com/mycelium-com/wallet/pull/367

**Comment by Giszmo** [comment]
Oh, hi Jochen. Thank you for reporting and thank you @prusnak for fixing. @jhoenicke if you could test this, I would merge it for our next release. Is not providing the change address backwards compatible all the way?

**Comment by jhoenicke** [comment]
> Is not providing the change address backwards compatible all the way?

Yes.  The address was just ignored by old firmware if present.
