### ISSUE TITLE
I don't remember my backup mycelium.

### ISSUE THREAD

**Issue by DarkLexsus** [mycelium-com/wallet#368]
Hi. In this day I change my Phone and now I don't remember my Backup PLS HELP ME. (on Mycelium)
Wallet: 18o4G8W1vVMv67JgM6QPndituhRbpmtBjE

**Comment by Giszmo** [comment]
Sorry but Mycelium is a be-your-own-bank kind of wallet. No third party can spend or rescue your money. If you lost both the wallet and your backup, there is no way of recovering it.

**Comment by MichelDiz** [comment]
Well, Giszmo, If I recover the files? Titanium Backup can backup the MyCelium's files? What are the crucial files for a possible recovery?

Best Regards.
