### ISSUE TITLE
Icon become a low resolution

### ISSUE THREAD

**Issue by patbec** [mycelium-com/wallet#371]
I've updated MyCelium to 2.8.12 (281201) and noticed that the app icon has become a low res version at the homescreen. Its not a real bug but not nice.

I use Android / LineageOS 14.1
Display 1920 x 1080 pixels (440 ppi)

**Comment by Giszmo** [comment]
thanks for reporting. We will look into this. It would be nice if you could confirm it was still good in version 2.8.11 or whatever version you know it was good as "we didn't touch this" ;)

**Comment by patbec** [comment]
Sorry for the late reply, I have set up a virtual machine with Android 7.1 (android-x86_64-7.1-rc1) and compare 3 versions.

Version 2.8.5 (28500) is OK
Version 2.8.11 (281100) is OK
Version 2.8.12 (281201) has a icon with a low resolution


I have attached 2 files that show the difference.

Version 2.8.5 and 2.8.11
![mycelium-28500-icon](https://user-images.githubusercontent.com/29308797/28594086-f0f7b7da-718e-11e7-8682-7b93a49d07fe.png)

Version 2.8.12
![mycelium-281201-icon](https://user-images.githubusercontent.com/29308797/28594085-f0f18dc4-718e-11e7-95a2-f899af294a0d.png)

**Comment by Giszmo** [comment]
this is fixed in the latest version
