### ISSUE TITLE
9/12 recovery words

### ISSUE THREAD

**Issue by TimJBenham** [mycelium-com/wallet#373]
Due to careful security I have only the last 9 of my 12 recovery words. Does code exist to do the exhaust over the first 3 words and what would be the work factor?

**Comment by jonathancross** [comment]
You should Google around a bit for [bip39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) brute force, maybe checkout [bip39bruteforce.c](https://github.com/trezor/trezor-crypto/tree/master/tools), etc. Seems there is about 8,589,934,592 possible combinations, any other info you have (eg xpub) could be useful, but this could be quite challenging.

PS: This is not the best place to have this discussion, better to post on: https://bitcoin.stackexchange.com

**Comment by TimJBenham** [comment]
That is good to know. 33 bits is not particularly difficult. In any event the delinquent heir has found their envelope, so it will not be necessary. Thanks for your time.
