### ISSUE TITLE
input validation for amount in bitcoin url

### ISSUE THREAD

**Issue by vv01f** [mycelium-com/wallet#377]
lets say a merchan has a poor implementation for showing a qr code to his customers that use mycelium as a wallet.
then it does happen, that they ancode more than 8 decimal places for the amount.
and mycelium is not able to deal with that but rejects the format as unknown.
according to BIP 21 there is no number of digits specified – although that should be clear to anybody in bitcoin this leads to incomplete information. maybe it is more helpful if the wallet did gracefully take input and validate it. thus do the rounding here.

I would like to ask for an improved string validation for *amountparam* on its value after delimiter '=' for the value of the *amount*.
also a more specific error message might help in other cases.

**Comment by Giszmo** [comment]
Please provide more info. If the amount is not clear, the amount should be ignored, so the user can specify it himself. Graceful parsing and guessing is probably not what we want here. Does it completely fail to read a QR if the amount is ambiguous?

**Comment by vv01f** [comment]
aye, ignoring amount would be a good step when the other parts (here address) are preserver.

simple reproduction of that error with an qr code (intentionally one decimal too much after delimiter):

    qrencode -t utf8 "bitcoin:1vvo1f7xSnZLAxwqATYvSpCCLMjNXcdNE?amount=0.123456789"

results in error message

    unknown format

**Comment by Giszmo** [comment]
![bla](https://user-images.githubusercontent.com/96378/29841467-e7ca54f2-8cdb-11e7-8a54-dfef3d463bd2.png)

**Comment by Giszmo** [comment]
![bitcoin:1vvo1f7xSnZLAxwqATYvSpCCLMjNXcdNE?amount=0.123456789](https://user-images.githubusercontent.com/96378/29841535-20054b06-8cdc-11e7-821f-a568236fcb11.png)

For the lazy ...

**Comment by Giszmo** [comment]
ok, we had similar bug reports and it's a slippery slope. If the payment request is invalid, should we really "recover"? What am I supposed to do with a payment request like this? Round up to the next Satoshi? Sure, if all wallets accept poor standard implementations, we will have to, too but for now I don't see it a pressing issue and prefer to leave it to the merchant to fix his url.

**Comment by vv01f** [comment]
Of course you have to make that choice; and in the particular case the bug was fixed on merchant side already. Just when people copy/paste things from calculators the same thing occurs and the current error message is easy overseen or not understood.

My perception of Mycelium was a user-friendly wallet.
just from users pov it might be better to give a more meaningful alert and be graceful, so (s)he can decide what to do without much hassle; including the hint to inform the other party of that possible source (here amount) of the problem.

But if you are fine with the current solution, I wont uphold the issue any longer.

**Comment by Giszmo** [comment]
The format is invalid. How can the message be more clear than that? Should we implement an explanation for every eventuality? "you misspelled bitcoin", "sorry, only one : there." ...

**Comment by vv01f** [comment]
from users pov this would be more helpful indeed. although you are exaggerating deliberately here.

of course, if you judge that current state the level you wanted to have, stick to it.
