### ISSUE TITLE
misleading display for account-internal transaction

### ISSUE THREAD

**Issue by vv01f** [mycelium-com/wallet#380]
when sending the hd-wallets collected amounts to one address of itself the unconfirmed transaction shows:

> Sending $fee BTC

And the current balance is only reduced by the fee.

I would say that is misleading (not representing the amount of the output towards my wallet). Although it should be OK to send funds without confirmation as long as I have the key; the actual transaction is not represented as it should.

besides: why would anyone do this? easy; getting rid of dust as long as there is lots of time to only afford a small fee. for then later saving time on fewer inputs. Another good usecase: transfer to segwit-address.
And yes, I could not use mycelium to create such a transaction as there is no option for custom fees or "use some dust as fee".

**Comment by Giszmo** [comment]
The transaction amount is currently calculated as the account's change in balance, lumping fee and transfered amount together. Summing them all up should get you to your final balance.

When you change a bag of coins into a $100 bill, paying a fee for that, representing this as one transaction is certainly not only $100 outgoing nor $100 incoming and granted, it's not the complete picture to only show the fee as if it was a spend but that is true for all transactions (that pay a fee).

For now, we should probably show your transaction as 0BTC + feeBTC and add a fee display to all outgoing  and optionally incoming transactions.

Later we will probably have to change things a bit, when we support RBF and one bitcoin transaction can accommodate multiple payments. A group of items, with each payment on its own line and just an equal line for the transaction fee.
