### ISSUE TITLE
Add mycellium to F-Droid store

### ISSUE THREAD

**Issue by LilChange** [mycelium-com/wallet#385]
F-Droid is a decentralized Android app store that is privacy conscious and only allows open source apps to be added. Learn more:

https://f-droid.org

Here are some developer docs if you want to self host the build with your own F-Droid repo:

https://f-droid.org/wiki/page/Setup_an_FDroid_App_Repo#Real_World_Setup

This should be pretty easy since you are open source. Hope your team is up for it.

**Comment by Giszmo** [comment]
F-Droid rejects our MS open source licence. Sorry. Maybe when we change our license.

**Comment by LilChange** [comment]
That is unfortunate. They are a bit strict on licenses. Would mycelium consider creating a self-hosted repo? Or potentially be ok with a third party running one with a build? Mycelium is perahps the best mobile wallet and it's unfortunate that due to licenes people must use google to install it securely.

**Comment by trymeouteh** [comment]
Man we need more good open source wallets on F-Droid since this is the only app store Degoogled android users have. Please consider changing the license since we would like a good multi crypto wallet
