### ISSUE TITLE
Unable to send payment to merchant-server. server responded with wrong ack mime-type

### ISSUE THREAD

**Issue by firestormdong** [mycelium-com/wallet#393]
I'm using mycelium testnet to test my merchant server. mycelium can get PaymentRequest from my server successfully, but it cannot post Payment.

It always shows "Unable to send payment to merchant-server. server responded with wrong ack mime-type".

I checked the response from my server and Content-Type is "application/bitcoin-paymentack" which should be the correct one according to [BIP 0071](https://github.com/bitcoin/bips/blob/master/bip-0071.mediawiki).

**Comment by Giszmo** [comment]
Would you mind debugging how that could happen? [This line](https://github.com/mycelium-com/wallet/blob/master/mbw/src/main/java/com/mycelium/wallet/paymentrequest/PaymentRequestHandler.java#L270) I suppose works. Else we should have gotten tons of complaints.

**Comment by firestormdong** [comment]
Was mycelium testnet in Google Play store built from master branch? I'm not familiar with Android development. But I can try.

**Comment by Giszmo** [comment]
any news on this? Sorry but I feel this is more an issue on your side. Let us know if we should re-open this as an issue.

**Comment by rraallvv** [comment]
I'm having this issue with bitpay.com
