### ISSUE TITLE
No Mycelium support? 

### ISSUE THREAD

**Issue by Paddieaaa** [mycelium-com/wallet#394]
You guys have not been giving support for over a week since I sent a ticket to info@mycelium.com. How long is your normal response time?

**Comment by Giszmo** [comment]
we currently have no support team. will see how far i get today.

**Comment by Paddieaaa** [comment]
Hi Leo

Thank you for the email.

I just need the procedure to get my RMC back into my account after sending
it to my mycelium Bitcoin address.

Thank you
Luhan Stoop


On 17 Sep 2017 9:30 PM, "Leo Wandersleb" <notifications@github.com> wrote:

we currently have no support team. will see how far i get today.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mycelium-com/wallet/issues/394#issuecomment-330077416>,
or mute the thread

**Comment by Paddieaaa** [comment]
Hi Leo

Thank you for the email.

I just need the procedure to get my RMC back into my account after sending
it to my Mycelium Bitcoin address.

Thank you
Luhan Stoop
