### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by juancmartinezg** [mycelium-com/wallet#396]
Cuando trato de hacer una transferencia me sale un mensaje "Formato no reconocido"

**Comment by Giszmo** [comment]
please provide more details.

**Comment by juancmartinezg** [comment]
En mi billetera tengo 4 BTC y cuando le doy lamopcion enviar escaneo el codigo de la billetera de destino y muestra error "formato no valido" y no deja trnasferir los fondos. Cuando ingreso la direccion manual me dice direccion no valida, pero de otra billetera si me funciona.. necesito recuperar mis 4 BTC pondrían ayudarme? Gracias



Enviado desde mi smartphone Samsung Galaxy.


-------- Mensaje original --------
De: Leo Wandersleb <notifications@github.com>
Fecha: 22/9/17 22:40 (GMT-05:00)
A: mycelium-com/wallet <wallet@noreply.github.com>
CC: juancmartinezg <juancarlosmartinezg@live.com>, Author <author@noreply.github.com>
Asunto: Re: [mycelium-com/wallet] Ayuda (#396)


please provide more details.

**Comment by Giszmo** [comment]
puede verificar cual es su versión de la billetera? Es del playstore? Espero que no sea la version Testnet :/

**Comment by Giszmo** [comment]
feel free to follow up but as this doesn't sound like a bug, I'm closing it.
