### ISSUE TITLE
There are any possibility to recover my wallet without seed or secret words?

### ISSUE THREAD

**Issue by nardonykolyszyn** [mycelium-com/wallet#397]
**My phone broke** and I had to reset it. I hadn't any seed, there's any possibility to recover my wallet with my Google Credentials (Email) or another question security? I'm desperate!

**Comment by jonathancross** [comment]
https://support.mycelium.com/hc/en-us/articles/207049775-MYCELIUM-BITCOIN-WALLET

>  If you lose your phone, or it gets wiped, and you don’t have a backup, your bitcoins will be lost forever.

There is some info [here about the wallet file](https://bitcoin.stackexchange.com/a/35796/13440), just in case you were using a backup program of some kind.

Good luck.

**Comment by Giszmo** [comment]
Also [this link](https://www.reddit.com/r/mycelium/comments/6twi4q/faq_did_i_lose_my_coins/) might help understand the situation better.
