### ISSUE TITLE
iPHONE

### ISSUE THREAD

**Issue by jpsteven** [mycelium-com/wallet#398]
So trying to get this set up but I'm told that it doesn't work on iPhone's? Says to go to Google play store in Apps, but when I do then what??? Not clear about how to proceed or if I should look for another option altogether. AND your video tutorial doesn't work, neither does this one: http://youtu.be/jV-29RFU6xA

**Comment by Giszmo** [comment]
this is the android repo. if you want to report a bug in the iPhone version, please use the other repo.

**Comment by jpsteven** [comment]
What other rep? And where, is there a link? I need more assistance or direction 

Stephen Kovacs
604-603-5477


----- Original Message -----
