### ISSUE TITLE
BTC not transferred in my wallet

### ISSUE THREAD

**Issue by JohnGre** [mycelium-com/wallet#400]
Hello,

Today I performed two BTC transactions. In the first one, I received the BTC without any problems on my public key. The second transaction performed, however, did not add any BTC on my account. Please note that after the first transaction, my public key has changed, but I used the old public key for the second transaction. On BLOCKCYPHER I can clearly see that the second transaction was successful, however my balance in the Mycelium wallet is still 0.
Please help me with this issue.

The public key for both transactions is : 1GJZp9p8k1wX9tGVaKWCXJgfb2Z3Nd3UKT

**Comment by Giszmo** [comment]
Issue resolved via mail
