### ISSUE TITLE
Mycelium wallet not importing all addresses

### ISSUE THREAD

**Issue by raducostea** [mycelium-com/wallet#401]
So i am using HD mycelium wallet with the payment gateway. I have generated about 100 addresses and about 15 of them have been paid and have confirmed amounts. The problem is that mycelium android app only sees 18 addresses and only 1 transaction. I checked the other addresses and they are derived correctly is just that they are not imported in my wallet. Is like mycelium doesn't want to check more derived addresses for existing balance.

**Comment by Giszmo** [comment]
Mycelium Bitcoin Wallet (this repo) follows more strictly the standard BIP44 that defines a gap limit of 20. If you are using gear, you might leave that standard, if 20 invoices in a row do not receive bitcoins. That is an incompatibility but not a bug in this wallet. Please check with gear.
