### ISSUE TITLE
Can't change currency to USD or anything else, but Bits, mBTc, or BTC.

### ISSUE THREAD

**Issue by milkiski** [mycelium-com/wallet#409]
^ I reinstalled the app and still happening...

**Comment by jamespotkukelkka** [comment]
I have the same problem. The only exchange provider I see is BitcoinAverage, but I can’t get any exchange rate.

**Comment by Giszmo** [comment]
That sounds like an [issue of the other of our wallets](https://github.com/mycelium-com/wallet-ios/issues/31).
