### ISSUE TITLE
transactions made using mycelium not showing up in mycelium

### ISSUE THREAD

**Issue by dooglus** [mycelium-com/wallet#41]
Yesterday I made a few transactions.  On two separate occasions the transaction  appeared to go through OK, but wasn't shown on the transactions display, and wasn't subtracted from my available funds.

I checked on blockchain.info and they had indeed been broadcast to the network, and upon pressing the refresh icon in mycelium they did appear in the app.

This seems like a dangerous behaviour, since I could have assumed the transactions hadn't been made, and sent them again, effectively paying someone twice by mistake.

I can understand connectivity issues possibly causing transactions not to be received from other devices, but these two were generated in the device which claimed not to know about them, which is strange to me.

I installed mycelium from the play store, so presumably have the current version installed.

**Comment by Giszmo** [comment]
I assume this old issue is fixed? Feel free to re-open.
