### ISSUE TITLE
don't consider unconfirmed change to be spendable

### ISSUE THREAD

**Issue by dooglus** [mycelium-com/wallet#44]
It appears to me that mycelium considers all change in the wallet to be spendable whether it is confirmed or not.

With the ongoing "malleable transactions" DDoS attack, that isn't a safe thing to do.  It's quite possible that change I created myself never confirms, due to a clone of my outgoing transaction getting confirmed rather than my transaction.

Would it be possible to add an option to prohibit unconfirmed change outputs from being considered as spendable?

**Comment by Giszmo** [comment]
The considerations from this issue are well known and taken into account in other issues that also try to improve problems arising from transaction chaining. I guess this particular issue can be closed.
