### ISSUE TITLE
PAY_TO_OPRETURN in Testnet?

### ISSUE THREAD

**Issue by phoniex1** [mycelium-com/wallet#481]
Hi,
I verify that mycelium don't support the script of PAY_TO_OPRETURN  in Testnet.
 Do you have the plan to support it in the future？
Thanks.

**Comment by Giszmo** [comment]
What do you mean by PAY_TO_OPRETURN? We use OP_RETURN where we need to (our supported colored coins) but I don't understand what is it that you want to achieve. Do you want to add OP_RETURN outputs to your normal transactions? If so, then I doubt we will support this. Please share what you want to achieve.

**Comment by phoniex1** [comment]
Thanks for your reply.
Yes, I want to use OP_RETURN to support colored coins or token based on BCH. Could you tell me that which version of mycelium support colored coins, or how to add the function of OP_RETURN on mycelium?
Thanks very much!
