### ISSUE TITLE
Offline signing

### ISSUE THREAD

**Issue by iceblue25** [mycelium-com/wallet#50]
Would be nice having the mobile wallet cosigned/signed offline with another smartphone phone in offline airplane mode. I think it is the cheapest easiest solution since many people have/will have a secondary/old smartphone. The two phones can communicate using QR codes using the camera. A similar  scheme to bitcoin armory but for mobile.

**Comment by Giszmo** [comment]
I like this idea and want it, too but with the emerging hardware wallets and TEE I guess it's obsolete. Feel free to re-open.

(Old android devices are generally a poor choice to put your private keys on.)
