### ISSUE TITLE
BIP38 Decryption Key Generation Stops on Device Rotation

### ISSUE THREAD

**Issue by alexenglish** [mycelium-com/wallet#52]
My device is an AT&T HTC OneX, Android 4.2.2.  Mycelium version 1.1.10.

When trying to spend from BIP38 encrypted cold storage rotate the device while it is generating the decryption key from your passphrase.  On rotation, the dialog showing the progress on generating the decryption key disappears and the process has stopped and must be restarted.

This is obviously not a critical bug, but is certainly annoying and seems like it should be easily preventable.

**Comment by Giszmo** [comment]
I hope and assume this is fixed. At least I found a commit reading "2014-09-11 10:44 Jan Dreske          o │ you can now do funky stuff while importing (like rotating the phone)" ;)
