### ISSUE TITLE
Failed restoration from PDF backup

### ISSUE THREAD

**Issue by eranst** [mycelium-com/wallet#60]
Hi
I am looking for help:

I have Mycelium wallet
I sent 1 mBTC and it has got into the wallet properly.
I backed it up to a PDF file with writing down properly the capital letters key

Now: i wanted to test a scenario of completely removal and re-installation on other device

I removed the application from my device
Then re-installed again

I open the new installed application (new address is automatically created) and then went to:
Menu -> Settings -> Expert Mode. i checked the Expert Mode with V.
Now, i got back to the main screen -> KEYS tab -> click on the upper Key+ icon and I scanned the Bitcoin address (left QR square) from the PDF backup. all worked OK. a new address (the original one, from the PDF) was created successfully. I have selected this address to be my main active address.

At this stage i could see my 1mBTC balance but couldn't use it for anything since my private keys has not been imported yet.

I went back again to the main menu -> Verify Backup and scanned the private key from the PDF (the right QR square), I typed in the decryption capital letters password correctly and got the message that my private key was imported successfully.

Now, the point is that although it seems like my private keys has been imported successfully, when I am going to BALANCE tab, there is no "send" button there. Moreover, click on the QR code is resulting in a message "Warning: your wallet does not have the private key for this address. You cannot spend coins received unless you have the private key elsewhere".

Please can help me with this? What am i doing wrong? what is missing here?

**Comment by Giszmo** [comment]
PDF backups are a legacy feature. If anybody is still struggling with this, please contact us via info@mycelium.com
