### ISSUE TITLE
UI settings to support different decimal mark, digit group options

### ISSUE THREAD

**Issue by haixiashi** [mycelium-com/wallet#66]
Can I suggest Mycelium UI settings to support different decimal mark and digital group options? For example, allow both comma ",", point ".", and space " ".

Current display (SI, some western European countries):
1 234.5678 mBTC
USD 1 234.56

North America:
1,234.5678 mBTC
USD 1,234.56

Some other European countries:
1.234,5678 mBTC
USD 1.234,56

**Comment by Giszmo** [comment]
Duplicate of #17
