### ISSUE TITLE
Add flat fee ability to sell orders

### ISSUE THREAD

**Issue by imkharn** [mycelium-com/wallet#73]
Please add the option to include a flat fee in the dollar price shown.

Currently we have to include a flat fee in the notes, and the system only supports percent based fees.

**Comment by Giszmo** [comment]
local trader is about finding local people to trade with *in person*. It's not like a day-trading feature where you compare on a global market. Therefore I find it essential to read the text and not reduce all to numbers.

On the other hand it should be rather simple to add a fixed fee to the display: "$500/BTC + $20". Sorting should be more about distance than about price anyway. Also the next will charge $3/mile to the meeting place?

I tend to close this.

**Comment by Giszmo** [comment]
local trader will be a module and change a lot if not get replaced. closing.
