### ISSUE TITLE
Local Trader: Replace reputation system with multi-signature addresses

### ISSUE THREAD

**Issue by renne** [mycelium-com/wallet#76]
Using a standard Bitcoin transaction a Bitcoin seller can receive funds (e. g. Euro) but refuse to transfer the bitcoins. Vice versa the bitcoin buyer can receive the bitcoins but refuse to send/hand over the funds. In both cases the other party looses it's funds completely.

The first approach to solve this were trustees like Mt. Gox which turned out to be a bad idea (850,000 bitcoins lost). The Local Trader program returns to a standard Bitcoin transaction with a reputation system. The reputation system reduces the risk of fraud but does not prevent it. It also limits the transactions of funds to personal handover.

So I suggest to use 2-of-2 multi-signature bitcoin addresses ([BIPS-0010](https://github.com/bitcoin/bips/blob/master/bip-0010.mediawiki)) to avoid fraud. When two parties have negotiated the conditions of a transaction (exchange rate, etc.) the mycelium wallet creates a multi-signature bitcoin address and the seller transfers the Bitcoins to that multi-signature address. From now on the seller can't transfer the Bitcoins back to his wallet without consent of the buyer and the buyer can't transfer the bitcoins into his wallet without consent of the seller. After the seller has received the funds he sends his private key of the muli-signature bitcoin address to the buyer who has both private keys, now.

To avoid abuse (seller does not disclosure the private key or buyer does not transfer/handover funds) an optional 2-of-3 multi-signature bitcoin address with an ombudsman can be used.

**Comment by Giszmo** [comment]
I guess if there was a decentralized escrow provider like in [Open Bazaar](https://openbazaar.org/) we could integrate 2of3 with that but like Rassah said, we don't intend to make us part of the transactions. Closing for now.
