### ISSUE TITLE
Unable to export to device or sd card

### ISSUE THREAD

**Issue by hughbragg** [mycelium-com/wallet#85]
I have file manager installed and I've tried several file manager apps, but none of them allow me to export the pdf to the local storage.
I would like this option and consider it safer than emailing the file to myself over the public internet or sharing on wifi.
This may be a bug on my devices, but I've tried on both my tablet and phone with the same result.

**Comment by Giszmo** [comment]
This issue is both fixed and legacy I guess. Closing.
