### ISSUE TITLE
Add a button like the trader one, but for goods and services.

### ISSUE THREAD

**Issue by ferni** [mycelium-com/wallet#89]
Make it possible to sell goods and/or services through mycellium, with bitcoin as the only payment option. It would behave sort of like the current trader feature except instead of "selling" fiat money for bitcoin, you would sell goods or services for bitcoin.

**Comment by Giszmo** [comment]
Yes, this is a great thing but in most areas globally there is not even enough people that sell cash. Having a more diverse market is something that needs heavy focused advertisement to bootstrap in one big city at a time.

I guess before Mycelium would bootstrap its own market it would rather provide a front end to [Open Bazaar](https://openbazaar.org/). @Rassah can we close this for now?
