### ISSUE TITLE
Restore-issue (2nd time restore on 2nd wipe. VZW Samsung s5)

### ISSUE THREAD

**Issue by mild7intl** [mycelium-com/wallet#96]
Restored fine the first time using encrypted PDF and written key.
Now that I rooted my phone, and got everything working, it seems to decrypt the key fine, but then says "unrecognized format" 

I think this is a bug, is there a workaround I can use? I don't have btc in the wallet, so its not a big deal, but my trader ratings are not bad so I want to use that account for now.

E

**Comment by Giszmo** [comment]
I guess this is not relevant anymore
